### ISSUE TITLE
virtual-scroll.js:73 Uncaught ReferenceError: __decorate is not defined

### ISSUE THREAD

**Issue by luisaceituno** [rintoj/angular2-virtual-scroll#1]
Hello. I'm using this with an Angular 2 final project created by the Angular-CLI, and I get the aforementioned error when starting my app. Any ideas?

**Comment by rintoj** [comment]
Hello, The bug is fixed and available with v0.0.3. Thanks for pointing out. The 'noEmitHelpers' in tsconfig was the culprit, cure found from [stackoverflow](http://stackoverflow.com/questions/36808303/webpackangular2-error-uncaught-referenceerror-decorate-is-not-defined)
