### ISSUE TITLE
datatable

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#10]
enhancement
what about datatable with your plugin with column header fixed like this https://github.com/swimlane/ngx-datatable

**Comment by rintoj** [comment]
It's ease to have fixed column header. See below.

```
@Component({
    selector: 'vertical-list',
    template: `
        <div class="header">
             <div class="col" *ngFor="let header of headers">{{header}}</div>
        </div>
        <virtual-scroll
            [items]="items"
            (update)="scrollItems = $event">
            <list-item *ngFor="let item of scrollItems" [item]="item"> </list-item>
        </virtual-scroll>
    `
})
export class VerticalListComponent {

    @Input()
    items: ListItem[];

    @Input()
    headers: string[];
}
```

**Comment by istiti** [comment]
Thanks for clean and easy example and easy api of your lib, even im not sure it works when window resize and horizontal scrollbar appear that all my column have same width, need more tricky things to get it working well

Will try, thanks

(Hope you will add more example soon and give more of your time to this library) to add feature and stay updated to last angular

Thanks @rintoj
