### ISSUE TITLE
List jumping when changing chunk

### ISSUE THREAD

**Issue by Worek** [rintoj/angular2-virtual-scroll#100]
Hi.
VS items are jumping, shaking and making party when scrolling through list. Sometimes items disappear from list and show after scroll. As i saw it happens when chunks are changed.

Also scrollInto is not reaching it destination, but stops in middle of way. 

Could you repair it or show me a way to repair it?

**Comment by rintoj** [comment]
Hi @Worek, please share your work, so that I can take a look at the problem

**Comment by Worek** [comment]
I cant becouse its company code. But In items i have several observables thet connect to services and http. As i think this is problem becouse angular is creating those items "in go" when scrolling throug list with your component.
To prevent it, could you show me how to Lazy Load List element by element. I mean when using ngFor load first element, after it is loaded, load second element etc...

**Comment by mitasovr** [comment]
Hi, I'v got same problem
1. Render array with a lot of items
2. `scrollInto(items[items.length -1])`
3. On some user action `items.push(newItem)`
4. Then `scrollInto(items[items.length -1])`
5. Repeat few times (3-5)

After that items are jumping on scroll. Actually scrolls container only, items just jumping and no changes in DOM

Unfortunately can't share my project

**Comment by whyboris** [comment]
I am unsure whether **my issue** was the same as described above, but I figured out the **solution** for my case.

**Issue:** I had a multi-column (5 columns, 6-10 rows depending on screen size) gallery (each item a custom component). Whenever the below or above items were created or destroyed, the gallery jumped by some number of pixels. It was especially easy to notice when smooth-strolling by clicking the middle mouse button and making the page auto-scroll only a few pixels per second.

**solution:** _for my case_ was simply that the `[childHeight]` I was setting was mismatching the actual component height. Once the height matched the component height, there was no more jumping.

Hope my experience is helpful at least to some 😄

**Comment by speige** [comment]
It appears that you're modifying the array directly with .push. This did not previously auto-refresh, so calling scrollInto immediately afterwards would not work. Instead you had to call virtualScroll.refresh() afterwards and possibly wrap the scrollInto inside a setTimeout(, 0). The lastest version of the package on npm tries to address this.

Please try the latest version & the above proposed solutions to see if it addresses your issue. Closing for now. Please re-open if you're still experiencing this issue.
