### ISSUE TITLE
Horizontal scrolling to load

### ISSUE THREAD

**Issue by EricsG95** [rintoj/angular2-virtual-scroll#102]
Hi Sir, appreciate your work. I have been trying to get this work on horizontal scrolling, but it almots looks like impossible. Could you expound on this for me? Whether it is technically possible?

**Comment by yossi-shasho** [comment]
+1

**Comment by marabesi** [comment]
duplicated https://github.com/rintoj/angular2-virtual-scroll/issues/28

**Comment by speige** [comment]
This is now an officially supported feature of the component. Please update to the latest version on npm & try it. Closing issue. Please re-open if you have more problems.
