### ISSUE TITLE
Does not show when the list only has a single item

### ISSUE THREAD

**Issue by ourarash** [rintoj/angular2-virtual-scroll#103]
No item is shown if the list length is 1. No update event is emitted.

**Comment by rintoj** [comment]
It works for the demo project (within this repo). Please see the screenshot below.

![image](https://user-images.githubusercontent.com/10824903/30102038-fd90eb9e-930b-11e7-8736-059f2c906cdc.png)

**Comment by patricknazar** [comment]
Did you ever work out what went wrong? I'm facing the same issue. Well, it's even worse than that. I always see N-1 items so if N=1 I see nothing, and if N=2, I see only one etc
