### ISSUE TITLE
Scroll bug (jerky, vibration) with "parentScroll" and variable item sizes

### ISSUE THREAD

**Issue by sitexw** [rintoj/angular2-virtual-scroll#104]
Hello,

I have a bug I do not use the "parentScroll" attribute with a custom HTML element and variable size item.
This creates a visual bug that jerks, vibrates or scrolls backwards.
This is an example, scroll to the bottom and you will see the bug :
https://plnkr.co/edit/g8WLBOgqDJjPsoffETEA?p=preview

Thank you.

**Comment by rintoj** [comment]
Hi @twjacobsen, It is not possible to implement a smooth scroll with items with variable size as in the example. All the calculations are based on the first item and first item only. So if other items in the list don't match the width and height of the first (visible) item in the list, the calculations would go wrong.

Considering every item's size in the list without affecting the performance is tricky. Please share if you have any ideas about how to fix this.

**Comment by twjacobsen** [comment]
If it's possible to scroll a number of pixels, it's possible to animate it.
Just scroll a subset of pixels every x milliseconds.

But the alternative of just providing a method of getting the number of
pixels to scroll, instead of scrolling, would be nice too.

**Comment by diegofalciola** [comment]
Setting a fixed height to my rows fixed the problem.
 I assume that some scenarios will not work here, but in my case I set the minimum height expected for the row. 

Doing this fixed the inner calculations issues while scrolling

thanks @rintoj

**Comment by kykint** [comment]
https://github.com/rintoj/angular2-virtual-scroll/pull/110 smooth scroll implemented here

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
