### ISSUE TITLE
Filter pipe being called too many times

### ISSUE THREAD

**Issue by LeXa777** [rintoj/angular2-virtual-scroll#106]
Hello,

I need to filter the items I provide to the virtual list with a pipe but the problem is: the pipe is run like 100s of times until I have to close the tab as it becomes unresponsive. I have taken out the virtual scroll and run my pipe on a simple ngFor just in case I have done something silly in the pipe itself, but without virtual scroll it's just getting called twice (which I think is normal for while running in development mode).

Any idea why this is happening and how to fix it?

Sample of my code:

```
<virtual-scroll [items]="items | myfilter:'test'" (update)="viewPortItems = $event">
        ....
</virtual-scroll>
```

Thanks,
Alex

**Comment by utkagarwal** [comment]
I too have the same problem.Have u found a solution @LeXa777 ?

**Comment by speige** [comment]
Closing this as whyboris solution is most likely correct. Please re-open if you're still experiencing this issue.
