### ISSUE TITLE
trackBy not working correctly

### ISSUE THREAD

**Issue by Idicious** [rintoj/angular2-virtual-scroll#107]
The trackBy function seems to always get an index instead of the item itself, here is the code I'm using:

`<virtual-scroll #scroll [parentScroll]="scroll.window" [items]="(service.items$ | async)">`
      `<item *ngFor="let item of scroll.viewPortItems; trackBy: trackByFn" [item]="item"></item>`
`</virtual-scroll>`

`public trackByFn(item: Item) {
      return item.id;
    }`

The value passed into the function is always number, and it seems to the be the index.

**Comment by rintoj** [comment]
Here is the signature of `trackByFunction`

```ts
interface TrackByFunction<T> { 
  (index: number, item: T): any
}
```

https://angular.io/api/core/TrackByFunction
