### ISSUE TITLE
total-padding is wrong when using multiple columns, and items doesn't fill last row

### ISSUE THREAD

**Issue by vegarda** [rintoj/angular2-virtual-scroll#108]
If I have 11 items of 100px height, in single-column the total-padding is correct: 1100px.

But if I use double-column, the total-padding is incorrect: 550px, when is should be 600px.

It makes the scrollbar jerky when you reach the bottom.

**Comment by rintoj** [comment]
This works fine with the demo project included in this repo. Please check this link for live demo: http://rintoj.github.io/angular2-virtual-scroll/#samples

I am assuming you would have missed to define the size of the children (both width and height).

**Comment by vegarda** [comment]
Shouldn't this work?

https://plnkr.co/edit/rlDGQe6Y5MtEFFtOAWfi?p=preview

**Comment by jonasbo** [comment]
Adding ceil fixes this:
    this.scrollHeight = d.childHeight * **Math.ceil**(d.itemCount / d.itemsPerRow);
I'm not really familiar with pull requests.

**Comment by vegarda** [comment]
@rintoj Please respond
