### ISSUE TITLE
IE demo sample not working

### ISSUE THREAD

**Issue by ananddc1989** [rintoj/angular2-virtual-scroll#109]
i am try to check the performance in IE11 using this link http://rintoj.github.io/angular2-virtual-scroll/#samples 

sample is not working in IE11, please fix it

**Comment by a139383** [comment]
@ananddc1989, Please feel free to raise a PR.

**Comment by subatomicglue** [comment]
Hangs the browser in IE11.  
We will need to find a (nother?) solution...
For the popularity / how many downloads/users of this project, surprised IE11 hasn't been solved..

**Comment by jaronwright** [comment]
This crashes IE11 for my app as well. Does anyone know if there is a fix for this? My boss is riding me to get this fixed!

**Comment by speige** [comment]
Unfortunately, this is too low a priority to troubleshoot since IE11 is a very old browser with a very small user base. If you really need to support IE11, please troubleshoot this yourself & submit a pull request or switch to a different component.

Closing.
