### ISSUE TITLE
angular cli use

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#11]
I try to use your lib inside my angular-cli project your last version and I get : 
`
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: VirtualScrollModule is not an NgModule
`

**Comment by rintoj** [comment]
Looks like this is a generic issue caused by a problem with [angular-cli@1.0.0.beta.24](https://github.com/angular/angular-cli/issues/3426). Temporarily workaround that works for me is to downgrade typescript to 2.0.10.

**Comment by bashome** [comment]
Hi Guys, I am getting this error today as well without the unhandled promise rejection ... just simply ... "ERROR in VirtualScrollModule is not an NgModule" at compile time.  I am on  angular-cli@1.0.0.beta.25 and have ensured that I have typescript@2.0.10.  

Wondering if it has anything to do with "NgModule" vs "ModuleWithProviders" but not really sure how to test that.  Seems to work fine when I build from source and run the demo.

**Comment by rintoj** [comment]
Fixed. Please check now. Feel free to reopen if you still face this issue.
