### ISSUE TITLE
 Template parse errors: Can't bind to 'item' since it isn't a known property of 'list-item'. 

### ISSUE THREAD

**Issue by francoro** [rintoj/angular2-virtual-scroll#113]
i have this error with the plugin. i installed like it said npm i angular2-virtual-scroll and i added to the app.module.ts in imports. this is the error:

 Template parse errors: Can't bind to 'item' since it isn't a known property of 'list-item'. 1. If 'list-item' is an Angular component and it has 'item' input, then verify that it is part of this module. 2. If 'list-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ties = $event">          <list-item class="list card card-item" *ngFor="let property of properties" [ERROR ->][item]="property" (click)="goFicha(property)" style="position: relative;">

I think its something like angular 4 doesnt recongnize the tag <list-item>

**Comment by francoro** [comment]
I solved using div tag inside <virtual-scroll>

**Comment by lousley** [comment]
I have the same problem in my angular 4 project. How do you solve the problem with div? Do you have an example?

**Comment by speige** [comment]
list-item is a made up component simply used as an example in the documentation. You have to create your own child component.

You can use a div instead of a custom component, however you can't use [item]="" on a div because that attribute doesn't exist. Instead you should use something like:

```
<virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <div *ngFor="let item of viewPortItems">{{item?.name}}</div>
</virtual-scroll>
```

Closing. Please re-open if you're still having issues.
