### ISSUE TITLE
[item] in list-item doenst work throw error

### ISSUE THREAD

**Issue by francoro** [rintoj/angular2-virtual-scroll#114]
this is the example
<virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <list-item *ngFor="let item of viewPortItems" [item]="item">
    </list-item>
</virtual-scroll>

this is my code

<virtual-scroll  class="cards-list-view" [items]="properties" (update)="viewPortItems = $event">
        <div class="list card card-item" *ngFor="let property of viewPortItems" [item]="property" (click)="goFicha(property)" style="position: relative;">
            <div>

and i have this error

```
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'item' since it isn't a known property of 'div'. ("rtItems = $event">

        <div class="list card card-item" *ngFor="let property of viewPortItems" [ERROR ->][item]="property" (click)="goFicha(property)" style="position: relative;">

            <div>
"): ng:///AppModule/ListingPage.html@204:80 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'item' since it isn't a known property of 'div'. ("rtItems = $event">

        <div class="list card card-item" *ngFor="let property of viewPortItems" [ERROR ->][item]="property" (click)="goFicha(property)" style="position: relative;">

            <div>
```

**Comment by sam-lex** [comment]
`<list-item *ngFor="let item of viewPortItems" [item]="item">`
In this example
`list-item` would be a component that has an `@Input` of item, hence `[item]="item"`

Since you're using a `div`, then there will be no `@Input` for `item`.
Here's my example:
```html
<virtual-scroll (update)="scrollItems = $event" (change)="onListChange($event)" [items]="sales">
  <div class="sale-renderer" *ngFor="let sale of scrollItems">
    <span class="date">{{sale.dtCreated}}</span>
    <span class="total">{{sale.total}}</span>
  </div>
  <div *ngIf="loading" class="loader">Loading...</div>
</virtual-scroll>
```

**Comment by francoro** [comment]
My problem is that i have a infinite scroll so when i add elements i doesnt keep the first 10 like the example that change the data in the elements, in mi case it adds the other 10 when i go to the end of the page.In the example its update the parent with transform and change the object data in my case it does not update

**Comment by sam-lex** [comment]
so you're saying that when you add another 10 elements, your first 10 elements disappears?  
are you doing perhaps like this?  
`this.items = newData;`  
If this is the case, then change it to:  
`this.items.push( ...newData );`

**Comment by francoro** [comment]
No, when i add 10 elements i do concat so when the first scroll to the bottom i have 20 items. What i want is like the example that it keeps the ten elements and only changes the data in the them. like this http://rintoj.github.io/angular2-virtual-scroll/

**Comment by speige** [comment]
If you modify the existing items array, you need to manually call virtualScroll.refresh(); It only auto-refreshes if you bind to a brand new array instance.

However, the latest version on npm attempts to handle this better. Try updating to see if it solves your problem.

Closing for now. Please re-open if you're still having issues.
