### ISSUE TITLE
Adding an ion-searchbar messes with the list height.

### ISSUE THREAD

**Issue by rcfrias** [rintoj/angular2-virtual-scroll#116]
I have an "ion-searchbar" and the list inside the "ion-content".  Both ui components work as expected, only the last item in the list get chopped out exactly the height of the ion-searchbar.  Not sure if it is possible to define a style height 100% - (searchbar height)...

**Comment by speige** [comment]
If you're still  experiencing this issue please submit a stackblitz to help troubleshoot it. Thanks.

**Comment by speige** [comment]
This is probably an app-specific issue & not a problem with the virtual-scroll component itself (unless it was a bug in a previous version that has since been fixed).

Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
