### ISSUE TITLE
Performance suggestion: Batch array slices into chunks

### ISSUE THREAD

**Issue by tstirrat** [rintoj/angular2-virtual-scroll#118]
Consider slicing the array at fixed chunk boundaries. It would reduce the number of times that change detection and `array.slice()` needs to run.

**Comment by speige** [comment]
@tstirrat What algorithm would you use to determine the boundaries? It seems difficult to predict the user's behavior: They might scroll 1 item at a time, or 1 page at a time, or by dragging the scrollbar to a random location.

Are you concerned about virtual-scroll changedetection (i.e. the calculateItems method?) or the changeDetection of your child components? There are other strategies to make your child components faster, such as OnPush changeDetection & simplifying your components.

Using larger chunks would render extra items in the DOM. I think in many cases this would be a worse performance tradeoff than re-running change detection.

virtual-scroll probably has some other optimizations that could be done. I'm new to the code base & need to read through it more. However, 
I believe Array.slice is very fast & is constant time whether the array is large or small. I think it just depends on the # of elements being retrieved, which for virtual-scroll should be quite small. So, that's probably not where I'd start when looking at optimizations.

Closing for now.

If you disagree with my opinion, I'm probably misunderstanding something. Please clarify for me. If you have other optimizations, please open a separate issue. Also, if you're able to code something that works faster, please submit a pull request.
