### ISSUE TITLE
transform(translateY) doenst update

### ISSUE THREAD

**Issue by francoro** [rintoj/angular2-virtual-scroll#121]
http://rintoj.github.io/angular2-virtual-scroll/#samples

I see in this example that when you scroll the parent it updates the transform(translate y) in my case it doesnt.

**Comment by speige** [comment]
@francoro would you mind submitting a code example or stackblitz? It'll help with troubleshooting this issue. Thanks.

**Comment by speige** [comment]
There's a good chance this is fixed in the latest version. Maybe try it out before creating the stackblitz. Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
