### ISSUE TITLE
bufferAmount leads to render of way too many items

### ISSUE THREAD

**Issue by niklas-dahl** [rintoj/angular2-virtual-scroll#122]
I have a list of 1000 items and I'am using this component like this:

```
  <virtual-scroll [items]="items" (update)="viewPortItems = $event" bufferAmount="10">

      <div *ngFor="let item of viewPortItems">
        item: {{item.num}} total show: {{viewPortItems.length}}
      </div>

  </virtual-scroll>
```

when using the virtual scroll component in my project without `bufferAmount` 37 items are rendered.
when setting `bufferAmount="10"` all `1000!` items are rendered.

Reproduced here: https://stackblitz.com/edit/angular-6q9pjj?file=app%2Fapp.component.html

Otherwise a great working component with an elegant api :+1:

**Comment by foxx9** [comment]
Hi,

you need to use `[bufferAmount]="10"` instead of `bufferAmount="10"`  so angular knows it's a number and not a string.

**Comment by niklas-dahl** [comment]
ah, I see, thanks for the answer :+1: 

you could consider casting the input value to a number (a single `+` cast in the right spot would do the trick) native html elements work like this, eg `<input type='number' min="1"  max="10">` but this is up to you..
