### ISSUE TITLE
How to handle vertical offset of the list

### ISSUE THREAD

**Issue by danielcrk** [rintoj/angular2-virtual-scroll#128]
First of all, this is really awesome, thanks a lot for your work!

I have a case where my list is not placed on top of the page, but you have to scroll down to get to it. What would be the best way to handle this? I'd rather not wrap the entire content with the virtual scroll element and treat the entire content as a "header", which I guess would be a possible solution.

Would it be possible to add an "offset" property?

Thanks again!

**Comment by danielcrk** [comment]
@rintoj any idea about this?

**Comment by danielcrk** [comment]
ping @rintoj :)

**Comment by whyboris** [comment]
I'm unsure I understand the challenge. Can you have this?
```
<div class="header">my content</div>

<div class="scroll-container">
  <virtual-scroll ...> ... </virtual-scroll>
</div>
```
Would this not work?

**Comment by whyboris** [comment]
Another solution may be to have the element which contains the virtual-scroll (and the scrollbar for the scrolling) to have style `top: 500px` giving you a bunch of space. And in that space you place  the header using `position: absolute`. Though this will not lot you scroll away from the header.

**Comment by speige** [comment]
I believe the best way to handle this is to leave the virtual-scroll in its current position on the page and use [parentScroll]="scroll.window" as explained in the documentation. This feature was hard to implement before, but should be easier now. You will only have 1 scrollbar and you will have to scroll past all the "header" content before you get to the virtual-scroll. One caveat is it's best not to have any content below the virtual-scroll or the user won't see it until they scroll to the very end of the page (which could be a very long scrollbar if your items array is large).

Another option would be to have 2 scrollbars, one for the window and 1 for the virtual-scroll, but this feels awkward from a user standpoint.

Let me know if you have issues getting parentScroll to work. You'll want to use the latest version of the package from npm. Also, read the updated documentation, & search through the past issues about parentScroll in this repo on github to see what others had to do to get it working.

Let me know if this solves your issues so I can close this. Thanks.
