### ISSUE TITLE
This is not working with ionic 3.6.1

### ISSUE THREAD

**Issue by tekkenking** [rintoj/angular2-virtual-scroll#129]
This is a very lovely work, but it doesn't seem to work with ionic 3.

This is the sample code
<virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <list-item *ngFor="let item of viewPortItems" [item]="item">
    </list-item>
</virtual-scroll>

The <list-item> is causing error of unknown element in ionic and when i changed to <div> and excluding [item]="item" am just getting a blank list.

For what its worth. am using lazy loading of Components

Any help would be appreciated. 

Thx

**Comment by danielcrk** [comment]
Not sure about that specific issue, but I don't think it is Ionic related, I use it with no problems at all. Without lazy loading tho.

Try removing [item]="item" from the list item (don't think it should be there), and try adding the [childHeight] property to the list. Missing that property could make the list appear blank.

**Comment by tekkenking** [comment]
Thanks for the reply.. I appreciate..

I did as you instructed. I added [childHeight] and also used <list-item> inside <virtual-scroll> here is the error i got.

`Runtime Error
Uncaught (in promise): Error: Template parse errors: 'list-item' is not a known element: 1. If 'list-item' is an Angular component, then verify that it is part of this module. 2. If 'list-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("tems]="items" (update)="viewPortItems = $event" [childWidth]="80" [childHeight]="230"> [ERROR ->]<list-item *ngFor="let item of viewPortItems; let i = index"> <ion-row ngClass="feed-content"): `

And if i change <list-item> to <div> it would just show and empty list.

Ionic virtual scroll works *ngFor works, but ofcourse ionic virtual scroll is too buggy and *ngFor is not good for very long list..

So am kind of suspecting this piece doesn't not support Lazy Loading.

**Comment by tekkenking** [comment]
Please i still need help with this anyone at home?

**Comment by medeirosrafael** [comment]
do you have a component called "list-item"?

**Comment by tekkenking** [comment]
I finally implemented list-item element and the error message disappeared.

Thanks

**Comment by abel672** [comment]
Hi does the child inside of the virtual-scroll needs to be a list-item component mandatory?. I am using like this (from docs): 

    <virtual-scroll [items]="array" (update)="viewPortItems = $event" [bufferAmount]="4">
      <div class="list-item" *ngFor="let item of viewPortItems">{{item}}</div>
    </virtual-scroll>

But also the virtual scroll is not working. all items are shown in the DOM at once. Even those that are not in the view right now.

**Comment by pcsantana** [comment]
@abel672 did you add to virtual-scroll a height style?

For example, in your ionic page.scss you should add something like this:
 ```
virtual-scroll {
        display: block;
        width: 100%;
        height: 700px;
    }
```

**Comment by Melcus** [comment]
Posted my solution here :  #85

**Comment by speige** [comment]
Closing. It appears the issue was due to incorrect usage of virtual-scorll & was resolved by the feedback given by other users. If the issue persists, please create a stackblitz to help with troubleshooting & re-open the issue. Thanks.
