### ISSUE TITLE
Removing and item for array does not update the list until user scrolls

### ISSUE THREAD

**Issue by blingerson** [rintoj/angular2-virtual-scroll#131]
If I have a list of items:

`<virtual-scroll
        (update)="themeItems = $event"
        [items]="themes"
        class="list-group">
        <theme-item
            class="list-group-item"
            *ngFor="let themeItem of themeItems"
            [theme]="themeItem"
            (onDeleteTheme)="deleteTheme( $event, confirmDeleteTheme )">
        </theme-item>
    </virtual-scroll>`

onDeleteTheme removes an item for "themes" which is bound to items.

Once removed calling refresh() does not  update the list. The item only gets removed once I scroll a little bit. Am I missing something here?

**Comment by blingerson** [comment]
The only work around I have found so far is removing the viewPortItems manually and calling update, but this means that the number of items shown is one less per delete until the user scrolls.

ie.
`this.virtualScroll.update.emit( pull( this.virtualScroll.viewPortItems, this.themeToDelete ) );`

**Comment by WhatzzUp** [comment]
I struggle with the same problem.

**Comment by rintoj** [comment]
@blingerson, can you try to make `themes` an immutable array? ie. when you remove a theme from the array make sure to create a new array:

```js
themes = themes.filter(theme => theme.id !== idOfThemeToBeRemoved)
```

**Comment by GlennVanSchil** [comment]
Any update on this?

**Comment by speige** [comment]
This should be fixed in the latest package on npm. Can you try it & let me know if it's still occurring? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Comment by blingerson** [comment]
@speige, this did indeed fix my issue. Thank you.
