### ISSUE TITLE
Merge pull request 110

### ISSUE THREAD

**Issue by kykint** [rintoj/angular2-virtual-scroll#135]
https://github.com/rintoj/angular2-virtual-scroll/pull/110
added smooth scrolling for non fixed-height elements

**Comment by pavimus** [comment]
This is very important feature for me, i vote for this!

**Comment by speige** [comment]
I've merged the PR (& modified it a bit). This issue should be working better now (not 100% perfect, but hopefully good enough). It's published to NPM (behind a flag documented in the readme). Could you try it out & close this issue if it's now resolved? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
