### ISSUE TITLE
Bug in "disposeScrollHandler" assignment

### ISSUE THREAD

**Issue by naharyd** [rintoj/angular2-virtual-scroll#136]
Hi,

I **think** there is  bug in your code related to resize, instead of assigning disposeResizeHandler handler to resize you are assigning disposeScrollHandler to resize
<pre><code>
this.zone.runOutsideAngular(() => {
        this.disposeScrollHandler =
          this.renderer.listen(parentScroll, 'scroll', this.refreshHandler);
        if (parentScroll instanceof Window) {
          <b>this.disposeScrollHandler</b> =
            this.renderer.listen('window', <b>'resize'</b>, this.refreshHandler);
        }
});
</code></pre>

Best Regards,
Dan

**Comment by speige** [comment]
Correct. Your pull request has been merged & a new version of the package is available on npm. Thanks for your contribution!
