### ISSUE TITLE
(end) not triggered on window

### ISSUE THREAD

**Issue by puppeteer701** [rintoj/angular2-virtual-scroll#137]
When virtual-scroll doesn't have a set height, ```(end)``` is never triggered, even though scrollbar is on the bottom.

**Comment by speige** [comment]
Could you try with the latest version of the package on npm to see if this issue is resolved? If not, could you submit a stackblitz or code sample to reproduce this? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
