### ISSUE TITLE
dropped support for parentScroll?

### ISSUE THREAD

**Issue by shanshanzoe** [rintoj/angular2-virtual-scroll#138]
is this parentScroll api already available? I installed from npm but looks like it's not working

**Comment by patrickracicot** [comment]
@shanshanzoe It seems to work, but their seems to be a bug where when you specify a `parentScroll`, the `virtual-scroll` element has the style `overflow-y:hidden;` applied which prevents the `parentScroll` to actually have a scroll.  Where I use it, overriding the style `overflow:visible` seems to fix it.

**Comment by natcohen** [comment]
Is it related (https://github.com/rintoj/angular2-virtual-scroll/issues/140)? If it is, I'll close it.

**Comment by nishesj** [comment]
Seems like [parentScroll]="scroll.window" is not working on latest version
instead you have to define window on component and use it like [parentScroll]="window"

**Comment by natcohen** [comment]
@nishesj Even by configuring the window, everything is messed up. If I set up the height of my `virtual-scroll` component, the scroll of my body remains small (`total-padding` has the right height but because it's in `virtual-scroll` which has only a limited height). If I don't set up the height of `virtual-scroll`, all the nodes are created...

Something seems to be broken in the design.

**Comment by nishesj** [comment]
have you tried giving your body fixed height ? something along height: 100vh;

**Comment by natcohen** [comment]
@nishesj Yes, I did...if you give a predefined height, no chance you'll get the scroll expanded anyway. I'm curious to understand how @a139383 intended to make it work because I don't see how it could ever work

**Comment by natcohen** [comment]
@nishesj I got it working! you were right, body needed a height!

**Comment by borriej** [comment]
Could someone please post a simple code example using window scrollbar as the scroll for the container? Im stuck at this. Tried setting body height, but this isn't working for me.

```
 <virtual-scroll [items]="myRides.controls" (update)="viewPortItems = $event" #scroll [parentScroll]="scroll.window" [childHeight]="71">

```
```
body{
  font-size: $font-size-base;
  min-height: 100vh;
  max-height: 100vh;
// overflow: hidden ... also tried this
}
```

**Comment by borriej** [comment]
Hi @rintoj, Is there any update on this? Im still having issues with double scrollbars. I would love to use the body scroll, please see image: https://ibb.co/n4ETKG

**Comment by Hristijan95** [comment]
`#scroll [parentScroll]="scroll.window"`

This obviously does not work. I've tried everything.

**Comment by tomschreck** [comment]
I'm not able to get virtual scroll parentScroll to work either.  I've set height = 100vh for body tag and no luck.  Has there been any progress on getting this fixed?  Can someone provide an example if they have it working please?


          <virtual-scroll
                  #scroll
                  [items]="ContactList" 
                  (update)="scrollItems = $event"
                  (change)="onListChange($event)"
                  [parentScroll]="body">

              <app-contact-card *ngFor="let item of scrollItems; let i = index" 
                                [contactModel]="item"></app-contact-card>
          </virtual-scroll>

body
{
height: 100vh;
}

Thanks.

**Comment by speige** [comment]
Would someone mind creating a simple example of implementing this in the "demo" folder of this repo's source code & submitting a PR? It'd be good to have for future testing & documentation.

I'm 99% sure it's working, because I'm using it in a separate more complex project. However, I haven't had time to extract it to a simple example yet. 

This would save me a bit of time so I can build more features & respond to other issues & pull requests. Thanks.

**Comment by speige** [comment]
I've added an example of this to the demo app that's part of this github repo.

**Comment by speige** [comment]
The demo is available on github. I'm waiting on rintoj to update it here:
http://rintoj.github.io/angular2-virtual-scroll/

Either way, I believe this issue is fixed.

Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
