### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by markballenger** [rintoj/angular2-virtual-scroll#14]
Downloading the repo and immediately running 'npm install' yields err! 

'prepublish' seems to be firing, running 'build', then fails at 'tsc'...

> > angular2-virtual-scroll@0.0.9 tsc c:\git\angular2-virtual-scroll
> > node_modules/typescript/bin/tsc
> 
> 'node_modules' is not recognized as an internal or external command,
> operable program or batch file.

npm -v 4.1.1 on windows

**Comment by rintoj** [comment]
Works fine for the following setup. Please feel free to reopen this issue, if you still see it.

## clone
![image](https://cloud.githubusercontent.com/assets/10824903/22925512/0c5d2332-f2cf-11e6-9032-1c320ea73dc0.png)

## npm install
![image](https://cloud.githubusercontent.com/assets/10824903/22925528/185b50aa-f2cf-11e6-9b99-36093e7ef479.png)

### node and npm versions:
![image](https://cloud.githubusercontent.com/assets/10824903/22925540/242cf47e-f2cf-11e6-803c-3192c8fa4599.png)
