### ISSUE TITLE
Use body scroll instead of container scroll

### ISSUE THREAD

**Issue by natcohen** [rintoj/angular2-virtual-scroll#140]
I would like to have the same behavior as this: http://developerdizzle.github.io/react-virtual-list/ (when Contained is not checked...). The list uses the scroll of the body instead of the virtual container.

I thought defining `[parentScroll]=window` would make it but I still get the scroll on my `virtual-scroll` container. Is it possible to achieve that or am I misunderstanding what `parentScroll` is?

PS `body` is obviously a parent of my `virtual-scroll` container but not its direct "father" - not sure if it could be an issue

**Comment by borriej** [comment]
@natcohen have you solved this? and could you post your code example? Im having issues with this. Cause im seeing two scrollbars while using [parentScroll]="scroll.window" https://ibb.co/n4ETKG

**Comment by natcohen** [comment]
@borriej Sorry for the delay, I was busy these days... Yes, I found a way to fix it. I rewrote part of this module in order to support table header and striped rows (by removing rows two by two).

Here is how I use it (pug):


    virtual-scroll([items]="list", [headerElement]='header', [parentScroll]="body", [bufferAmount]='3', (update)="visibleElements = $event", [childHeight]="49")
        table.table.table-striped(#table='', style='table-layout:fixed;')
            thead(#header='')
                tr
                    th Header
            tbody
                tr
                    td Cell

And the rewritten module is here: [virtual.component.ts.txt](https://github.com/rintoj/angular2-virtual-scroll/files/1703419/virtual.component.ts.txt)

**Comment by borriej** [comment]
@natcohen ah this is really kind of you! Thanks, i'll test this in the coming days!

**Comment by speige** [comment]
@natcohen Would you please submit a pull request for the support for table header & striped rows? I can merge & update npm. I think it'd benefit other developers using this component. Thanks!
