### ISSUE TITLE
Compatibility with Dragula

### ISSUE THREAD

**Issue by Laoujin** [rintoj/angular2-virtual-scroll#142]
Dragula Drag&Drop library: https://github.com/valor-software/ng2-dragula

The problem:  
```
<div dragula="my-bag" virtualScroll...>
    <list-item />
</div>
```

Generates:  
```
<div dragula="my-bag" virtualScroll...>
    <div class="total-padding" />
    <div class="scrollable-content>
            <list-item />
    </div>
</div>
```

I think that being able to put the `[dragula]` attribute on the `div.scrollbable-content` would fix the Dragula functionality.

Is there any way to put certain classes/inputs etc on the .scrollable-content?

**Comment by oktav777** [comment]
Maybe this will not solve your problem with [dragula](https://github.com/valor-software/ng2-dragula), but I use [ng2-dnd](https://github.com/akserg/ng2-dnd) and it works like a charm with ~500 areas in `virtual-scroll` that listen for `drop` event.

**Comment by Laoujin** [comment]
We've copied the virtual-scroll source and adjusted the `scrollable-content` container div.

Far from ideal but it works...

```
@Component({
  selector: "virtual-scroll,[virtualScroll]",
  exportAs: "virtualScroll",
  template: `
    <div class="total-padding" #shim></div>
    <div class="scrollable-content" [dragula]="'dragula-bag'" #content>
      <ng-content></ng-content>
    </div>
  `,
```

**Comment by shohrukh92** [comment]
This option is also works fine:
```
          <ul>
            <virtual-scroll
                [items]="model"
                (update)="viewPortItems = $event">
                <div [dragula]='"bag-one"' [dragulaModel]='model'>
                    <li *ngFor="let item of viewPortItems"> ... </li>
                    ...
```

**Comment by speige** [comment]
Closing as shohrukh92 has suggested a workaround.

**Comment by samsamm777** [comment]
@shohrukh92 I cant get your workaround to work. The extra div caused only some of the items list to show.

**Comment by speige** [comment]
@samsamm777 would you mind creating a stackblitz to help troubleshoot your issue?
