### ISSUE TITLE
Scroll with variable height is very jerky

### ISSUE THREAD

**Issue by ourarash** [rintoj/angular2-virtual-scroll#145]
I'm this setup:

```
<virtual-scroll (update)="viewPortItems = $event" 
        [items]="posts" 
        *ngIf="showRintoj" 
        (end)="fetchMore($event)" 
        (start)="rintojRefresh($event)"
        [childWidth]="200"
        [childHeight]="350"
        >
          
     <post-info [post]='post' *ngFor="let post of viewPortItems; let i = index " (deletedPost)='onDeletedPost(i)' [options]='postInfoOptions'>
     </post-info>
               
</virtual-scroll>
```

And I do not lock the height of each item, but the result is that the scroll is very jerky. Is variable height supported? I really appreciate if someone can post an example of items with variable height that works smoothly.

**Comment by ourarash** [comment]
I noticed when I do npm install, I don't get the latest version.  I used method 1 discussed [here](https://github.com/rintoj/angular2-virtual-scroll/issues/126), and was able to make it work, but now the end event doesn't fire. Is this the right way to do it?

**Comment by kykint** [comment]
I'll recheck end event. It was working previously.

**Comment by loctrice** [comment]
I need variable height as well. It skips over items and does random scrolling when my items are different sizes. I can't use the most recent version because I'm on angular2.

**Comment by ScottSpittle** [comment]
@loctrice https://github.com/rintoj/angular2-virtual-scroll/pull/110

**Comment by loctrice** [comment]
This looks like it was merged in after 3.0 - which means it's not compatible with angular2, only angular 4.

**Comment by checkthemethod** [comment]
@lotrice, were you able to resolve this issue with the random jumping scrolling?

**Comment by loctrice** [comment]
I wasn't. I had to update my project - which was painful.

**Comment by speige** [comment]
I've merged the PR (& modified it a bit). This issue should be working better now (not 100% perfect, but hopefully good enough). It's published to NPM (behind a flag documented in the readme). Could you try it out & close this issue if it's now resolved? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
