### ISSUE TITLE
scrollInto with variable height problem

### ISSUE THREAD

**Issue by zjw1918** [rintoj/angular2-virtual-scroll#147]
scrollInto() with variable height, only takes the min height as the offset?

**Comment by kykint** [comment]
https://github.com/rintoj/angular2-virtual-scroll/pull/110 Fixes are here

**Comment by speige** [comment]
I've merged the PR (& modified it a bit). This issue should be working better now (not 100% perfect, but hopefully good enough). It's published to NPM (behind a flag documented in the readme). Could you try it out & close this issue if it's now resolved? Thanks.

**Comment by zjw1918** [comment]
thanks a lot
