### ISSUE TITLE
Observable input

### ISSUE THREAD

**Issue by DanGraZisson** [rintoj/angular2-virtual-scroll#15]
Good day, I'ev just started trying out your virtual scroll and I'm having difficulities making it work with an observable collection.

`    <virtual-scroll [items]="persons" (update)="viewPortItems = $event">
            <Contact *ngFor="let item of viewPortItems" [person]="item"></Contact>
    </virtual-scroll>`

Where "persons" is an Observable<PersonModel[]>.
The HTML code works when I use mocked data.

Am I using it wrongly, not having it set up correctly, or is it simply not supported at this time?

**Comment by DanGraZisson** [comment]
So I solved the problem on my end.
The problem wasn't the observable input, it was the dynamic nature of the component, even so that even with setting ChildHeight and ChildWidth to reasonable numbers the virtual scroll ended up trying to create a HTML component for each of the 15000 test data components.
I solved this by copying over the virtual scroll to do local debugging, I ended up creating a 
 `@input() maxRows: number`
and in the `calculateItems()` method I added `if (end == 0 || (end - start) > this.maxRows) {
            end = this.maxRows + start;
        }`
I would do a pull request but I do not know how to use git or how to show it on GitHub.

**Comment by PillowPillow** [comment]
Hello Dan, I'm pretty sure that this library simply doesn't handle the observable since all methods use the *items* input as a basic array. 
`items = this.items || [];`
The issue you found is just that the lib try to calculate the length of an observable without subscribing to it and get the value.

Concerning the pull request, you just have to fork this repo, clone the new one, do the modif and create a pull request from the fork.

best regards
Nicolas

**Comment by DanGraZisson** [comment]
Hello Nicolas, I did do some changes to the items so it could accept observables as well, thing is we've implemented out own observables so they can be treated as an array but it isn't an array, so what I did was loosen up the checks for wheter it is an array or not, but I'm unsure if I should share that part of the changes since as it is it works with my solution but I'm afraid it may not be what you or users of this library want.

I'll try to create a pull request so you can see what I did for the maxRows input so you can implement/merge it into the library if you see it being usefull.

**Comment by rintoj** [comment]
Hello Dan, as Nicolas, mentioned this lib works with array, not observables. So you should add `async` pipe in your code to make it work with observables.

```
<virtual-scroll [items]="persons | async" (update)="viewPortItems = $event"> <Contact *ngFor="let item of viewPortItems" [person]="item"></Contact> </virtual-scroll>
```

Try:
` [items]="persons | async`
