### ISSUE TITLE
angular2-virtual-scroll with flexLayout

### ISSUE THREAD

**Issue by maku** [rintoj/angular2-virtual-scroll#150]
I have problems to use angular2-virtual-scroll together with flexLayout (https://github.com/angular/flex-layout).

.e.g. I want display some kind of cards in a row with wrapping. The number of cards depend on the screen size

```
<div  fxLayout="row" fxLayoutWrap="wrap" style="padding: 10px;">
    <div class="list-item" *ngFor="let item of cards" fxFlex="25" fxFlex.md="33" fxFlex.sm="50" fxFlex.xs="100">
      Title {{item.title}}
    </div>
</div>
```

How can I reach this kind of functionality within virtual-scroll 

I prepared sample code in stackblitz (https://stackblitz.com/edit/angular-material2-issue-agditq) where I tried the 2 versions (with virtual-scroll and withouth). But I don't get it how to do it...

Can anybody help??

TIA

**Comment by evxn** [comment]
Hi, @maku. Were you able to somehow solve this issue?

**Comment by speige** [comment]
Did the answer from ScottSpittle resolve your concern? I'm closing this for now. Please re-open if you're still having issues.
