### ISSUE TITLE
has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by awaisaltaf** [rintoj/angular2-virtual-scroll#154]
I just installed and add into modules and getting this error. has no exported member 'Renderer2'.

**Comment by abmnukmr** [comment]
I have same issue

**Comment by loctrice** [comment]
Renderer2 works with Angular 4 not Angular 2. It looks like this issue is caused from using the most recent version in an angular 2 app. From what I can tell from issue #139 we can use a prior version of virtual scroll, but I haven't tried it yet.

**Comment by speige** [comment]
Correct. Angular2.x is only supported in an earlier version of this package.
