### ISSUE TITLE
end event doesn't work properly

### ISSUE THREAD

**Issue by maxim1006** [rintoj/angular2-virtual-scroll#157]
Please add proper end scroll event

 if (end !== _this.previousEnd && _this.startupLoop === false) {
                    _this.end.emit({ start: start, end: end });
                }

this condition isn't right

**Comment by andreandev** [comment]
Hi @maxim1006,
Did you find a better code?
Me too doesn't work.

**Comment by speige** [comment]
Please try the latest code on npm to see if your problem still exists, it has a few bug fixes. If it's still ocurring, please describe what's wrong with the current event being emitted & possibly submit a stackblitz to help me troubleshoot. If you know what code needs to be changed, please submit a pull request. Thank you.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
