### ISSUE TITLE
Unable to use scrollInto() method with bufferAmount prop

### ISSUE THREAD

**Issue by WandersonAlves** [rintoj/angular2-virtual-scroll#164]
If i use a non-default value for bufferAmount, the scrollTo() doesn't work properly.

This code snippet return a wrong value:

```
var scrollTop = (Math.floor(index / d.itemsPerRow) * d.childHeight)
            - (d.childHeight * Math.min(index, this.bufferAmount));
```

I tested with 25 as `bufferAmount` and `scrollTop`was equal zero

My `this.calculateDimensions()` returns this:

```
{
  "itemCount": 53,
  "viewWidth": 412,
  "viewHeight": 660,
  "childWidth": 360,
  "childHeight": 125,
  "itemsPerRow": 1,
  "itemsPerCol": 5,
  "itemsPerRowByCalc": 1,
  "scrollHeight": 6625
}
```

**Comment by speige** [comment]
I've submitted a new version to npm with various bug fixes. Could you try that & see if it resolves your issue? If not, could you submit a code sample or create a stackblitz to help me troubleshoot it for you? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
