### ISSUE TITLE
update event not always giving all available/viewable items

### ISSUE THREAD

**Issue by GlennVanSchil** [rintoj/angular2-virtual-scroll#169]
I have list using the infinite scroll with a search input on top.
![selection_014](https://user-images.githubusercontent.com/3930037/34982953-40e3cdbe-faac-11e7-890a-56a29129a8ca.png)

Whenever I start typing it does update the list correctly. The updated list is a new list from an API call that replaces the current list.
![selection_015](https://user-images.githubusercontent.com/3930037/34983087-a45ad4fa-faac-11e7-84b4-3cf5f84e5c62.png)

If I now remove the last character I expect to see all the viewport items with torfs x, but instead I see only 2 entries but the scroll bar does indicate it has more items
![selection_016](https://user-images.githubusercontent.com/3930037/34983148-e15bb07c-faac-11e7-8136-8a8dbe35ca91.png)

If I now scroll or remove yet another character it shows the correct result
![selection_017](https://user-images.githubusercontent.com/3930037/34983184-005b03f6-faad-11e7-9b1f-1fd1bc602446.png)

When I look at my console output. I can see the update event only return 2 items, although my list containing all the items is correct
![selection_018](https://user-images.githubusercontent.com/3930037/34983275-44714924-faad-11e7-8a0a-18aa08a61aad.png)

**Comment by GlennVanSchil** [comment]
Found the problem. 
i had the following css
```css
tbody {
    display: block;
    min-height: 100px;
    max-height: 300px;
    overflow: auto;
}
```
whenever I had only one table row left, my height would be 100px. If I now added more elements by removing characters from the searchbox the viewport height would still be calculated on that 100px instead of the 300px I expected.  So to solve this I replaced the min and max height with a static height of 300px.

For my personal case the issue is closed because it still fits my design, but might not be a solution for everyone though. so not closing it yet

**Comment by speige** [comment]
I'm closing this since there's an existing workaround. The documentation does specifically state that a static height is needed. You might try adding a javascript event handler for when the height changes & calling .refresh()

This is discussed in the documentation under "If container size changes".
It seems possible to have virtual-scroll monitor for size changes, rather that making the developer do it. It should be fairly easy. If either of you is interested in coding this, please submit a pull request. Thanks.

**Comment by insomnia1337** [comment]
bump how to resolve this problem?
