### ISSUE TITLE
Virtual Scroll with Reactive Forms - FormArray

### ISSUE THREAD

**Issue by borriej** [rintoj/angular2-virtual-scroll#170]
Hi,

thanks for the module. I have a question: 

> does virtual-scroll work with a large Reactive Form with a Form Array? 

Because index changes with virtual-scroll and whilst typing, my values appear in multiple input's instead of 1.

```
        <div formArrayName="rides">

             <virtual-scroll [items]="myRides.controls" (update)="viewPortItems = $event" #scroll [parentScroll]="scroll.window" [childHeight]="71">

                <div *ngFor="let ride of viewPortItems; let i=index; trackBy: trackByFn" [formGroupName]="i">

                    <div class="ride d-flex">
                       <!-- inputs here which are bound using formControlName="" -->
              
                    </div>

```

**Comment by rintoj** [comment]
@borriej, virtual scroll will work fine if the height of each item is same. Variable height is not working well at the moment. We have some work in progress.

**Comment by borriej** [comment]
@rintoj Since Virtual Scroll hijacks the index :P 

I got the reactive form array working with a work around. By keeping a manual index parameter on the formGroup object itself, and passing it into [formGroupName]="ride.i" instead of "i". So when Virtual Scroll takes index 9-19... i would previously be index 0-10 (because thats just the amount of elements in the component).. but with "ride.i" it is the real index: 9 - 19!

**Comment by rintoj** [comment]
@borriej, got your problem. I will see if I can add an original index to component so that you don't have to keep an external index parameter.

**Comment by borriej** [comment]
aahhh sweet @rintoj !! 💯

**Comment by ciesielskico** [comment]
+1

**Comment by borriej** [comment]
is there an update on this? :)  and is it possible to have dynamic height on items? Because of validation messages per formGroup in the formArray.

**Comment by speige** [comment]
I've merged the PR (& modified it a bit). This issue should be working better now (not 100% perfect, but hopefully good enough). It's published to NPM (behind a flag documented in the readme). Could you try it out & close this issue if it's now resolved? Thanks.

I'm not certain if your issue was related to different-sized child items or not, so maybe that PR is unrelated. If so, maybe you can clarify your issue or create a stackblitz?

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
