### ISSUE TITLE
ERROR Error: Expected to not be in Angular Zone, but it is!

### ISSUE THREAD

**Issue by vegarda** [rintoj/angular2-virtual-scroll#172]
I get this error in EDGE when I try to open a PrimeNG multi-select dropdown.

Error Expected to not be in Angular Zone, but it is! Error 'Expected to not be in Angular Zone, but it is!' Error: Expected to not be in Angular Zone, but it is!
   at NgZone.assertNotInAngularZone (eval code:4715:13)
   at VirtualScrollComponent.prototype.calculateItems (eval code:205:13)

**Comment by speige** [comment]
There is an undocumented property [doNotCheckAngularZone]="true" which should solve your problem. I don't know the purpose behind this or if it will cause other issues. If you're able to find a better solution, please submit a pull request. Until then, I'm closing this issue as there is a workaround. Please re-open if you have further problems. Thanks.
