### ISSUE TITLE
Not Angular 2 Compatible

### ISSUE THREAD

**Issue by loctrice** [rintoj/angular2-virtual-scroll#173]
The documentation states this is an Angular 2 compatible module. Issues #139 and #154  show an error that is caused by compatibility issues between Angular2 and Angular4.

**Comment by molikmiah** [comment]
Version 0.3.0 was the last version compatible with Angular 2.x, after this version a commit was made to introduce Renderer2 which is only available in Angular 4+

The versioning is not semantic versioning and there is a breaking change from v0.3.0 to v0.3.1.

Please address this.

**Comment by speige** [comment]
Sorry about that. We don't currently support SemVer, but will try to do this in the future. For now, if you need to use older versions of Angular please look at the history of package.json & find the commit with the correct angular dependencies for your project & use that specific commit (or npm version) in your project's package.json (without ^or ~ ). Unfortunately this means you won't get any bug fixes or new features until you upgrade to a newer version of Angular.

Sorry for the inconvenience.

Closing this for now.

If you know of a way to support both older & newer versions of Angular with the current code base (ex: downgrading version #s in package.json), please submit a pull request. Thanks.
