### ISSUE TITLE
Kanbanboard structure (swimlanes with columns)

### ISSUE THREAD

**Issue by gentle9** [rintoj/angular2-virtual-scroll#174]
Hi,

is it possible to use the virtual scroll within child items like in a kanban board with swimlanes and multiple columns?
For example I have this structure.
```
RootLevel{
  name: string;
  childlevels: Childlevel[]; 
}

Childlevel {
  name: string;
  col1: any[];
  col2: any[];
  col3: any[];
}
```

My HTML template will look like this.

```
<div class="kanban-root-swimlane" *ngFor="let root of roots">
 Rootname: {{root.name}}
    <div *ngFor="let child of root.childlevels">
     <div class="col1" *ngFor="let col1Item of child.col1"><div class="card">{{col1Item}}</div></div>
     <div class="col2" *ngFor="let col2Item of child.col2"><div class="card">{{col2Item}}</div></div>
     <div class="col3" *ngFor="let col3Item of child.col3"><div class="card">{{col3Item}}</div></div>
    </div>
</div>
```

So this means there are like some swimlanes (groups) which are the rootlevel. Each of the lane has 3 columns and in each column there is the content which are the cards in a kanban board. 
Now I can have many cards and need some virtual scroll do get this working with a good perfomance but I dont know if it is possible. I have seen your multi-column example but I don´t think that it will work in this case.

**Comment by speige** [comment]
I believe this is possible, yes. However, I don't have the time or ability to help you code the solution. I'm closing this issue. If you have a specific problem with the component, please open a separate issue. Thanks.
