### ISSUE TITLE
How can I use it with dynamic components?

### ISSUE THREAD

**Issue by vitstr** [rintoj/angular2-virtual-scroll#179]
Hello, @rintoj 
How can I use the angular2-virtual-scroll with [dynamic components](https://angular.io/guide/dynamic-component-loader)? Could you provide an example of it?

**Comment by lucasbasquerotto** [comment]
@vitstr I made it work using the `childHeight` property (I don't know if your case is the same though):

```
<virtual-scroll [items]="items"
    [childWidth]="80"
    [childHeight]="30"
    (update)="viewPortItems = $event">

    <list-item *ngFor="let item of viewPortItems" [item]="item">
    </list-item>

</virtual-scroll>
```

**Comment by speige** [comment]
@vitstr did lucasbasquerotto solve your issue? Closing for now. Please re-open if needed.
