### ISSUE TITLE
Use *ngIf or filter for list item

### ISSUE THREAD

**Issue by amitwagh17** [rintoj/angular2-virtual-scroll#183]
There is no way to hide or filter virtual scroll list item based on flag. ViewPortItems are not skipping items that satisfy *ngIf condition

**Comment by lucasbasquerotto** [comment]
@amitwagh17 You could try to filter the items before displaying:

`this.items = (items || []).filter(item => item.flag !== someFlag);`

**Comment by speige** [comment]
lucasbasquerotto is correct. You have to filter the items array before you pass it to virtual-scroll.
