### ISSUE TITLE
Scrollbar flickers on init

### ISSUE THREAD

**Issue by iskathi** [rintoj/angular2-virtual-scroll#185]
When creating list for the first time and scroll parent is window, scrollbar flickers for a brief moment.
Occurs because child height is set to window height and everything is calculated using that row height.

```
      contentDimensions = content.children[0] ? content.children[0].getBoundingClientRect() : {
        width: viewWidth,
        height: viewHeight
      };
    let childWidth = this.childWidth || contentDimensions.width;
    let childHeight = this.childHeight || contentDimensions.height;

```

**Comment by speige** [comment]
Could you try the latest version of the npm package to see if this is still occurring? If so, could you submit a code sample or create a stackblitz? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
