### ISSUE TITLE
Question: how to solve my problem?

### ISSUE THREAD

**Issue by Fokir** [rintoj/angular2-virtual-scroll#186]
There is a task with the use of your module, but I encountered a problem when implementing it.
I need some elements to have a double height, like in the screenshot
![-2](https://user-images.githubusercontent.com/1648384/37652636-926da58a-2c55-11e8-93cc-9630a48af097.png)
I'm not quite sure how to solve this problem competently without using empty elements of the array

PS. Sorry for my rough sketch

**Comment by ScottSpittle** [comment]
https://github.com/rintoj/angular2-virtual-scroll/pull/110

**Comment by speige** [comment]
I've merged the PR (& modified it a bit). This issue should be working better now (not 100% perfect, but hopefully good enough). It's published to NPM (behind a flag documented in the readme). Could you try it out & close this issue if it's now resolved? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
