### ISSUE TITLE
usage with horizontal scroll

### ISSUE THREAD

**Issue by DoryZi** [rintoj/angular2-virtual-scroll#188]
Great work man!
Do you plan to add horizontal scroll to it? 
I have a horizontal scroll in my app and I need this to work there, can it work there as is?
If not do you plan to add support for that?

**Comment by speige** [comment]
DoryZi, I've merged your pull request & this is now an officially supported option. Please try out the latest version of the npm package & let me know if you have any issues. Thanks.
