### ISSUE TITLE
nothing displays

### ISSUE THREAD

**Issue by humblepride** [rintoj/angular2-virtual-scroll#189]
i create a github repo for this issue:
[link](https://github.com/humblepride/angular2-virtual-scroll-show-nothing)
if i set `childHeight`, all items will be rendered.

deps:
```
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular2-virtual-scroll": "^0.3.2",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
```
btw: i use cnpm instead of npm(if this matters...)

**Comment by CoryCharlton** [comment]
Yes it works with with Angular 5 (I'm running 5.2.9). If your items do not have a fixed height/width you may need to set the childHeight and childWidth properties for it to work correctly. The README.md outline this and I've copied it here for reference:

## Items with variable size

Items must have fixed height and width for this module to work perfectly. However if your list happen to have items with variable width and height, set inputs `childWidth` and `childHeight` to the smallest possible values to make this work.

```html
<virtual-scroll [items]="items"
    [childWidth]="80"
    [childHeight]="30"
    (update)="viewPortItems = $event">

    <list-item *ngFor="let item of viewPortItems" [item]="item">
    </list-item>

</virtual-scroll>
```

**Comment by humblepride** [comment]
i made some test and finally figured it out.
**u need to set `style-width` to virtual-scroll element.**
nothing to do with `childWidth` or `childHeight`
