### ISSUE TITLE
Property 'viewPortItems' does not exist

### ISSUE THREAD

**Issue by amit-kiwi** [rintoj/angular2-virtual-scroll#198]
I have the issue in server side rendering angular5 project when i implemented i got this error.
Property 'viewPortItems' does not exist. 
**and its working fine in normal angular 5 project**

**Comment by speige** [comment]
I'm not able to reproduce this. Can you try with the latest version of the npm package & see if it's still happening? If so, maybe you can share you code or create a stackblitz?

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Comment by nisitkaswaninsta** [comment]
+1

**Comment by speige** [comment]
@nisitkaswaninsta could you share some code that causes this error? I'm unable to reproduce. Thanks!
