### ISSUE TITLE
the number of raw is wrong in initial case

### ISSUE THREAD

**Issue by Healer1111** [rintoj/angular2-virtual-scroll#202]
On page rendering, it always display two rows data. Other data is blank. When I debug in virtual-scroll, I found the result of calculation is wrong. It seems that it is not to get the right height to calculate. When I manually invoke the method refresh() in constructor, this issue can be addressed. But in IE browser, the process of loading the following blank row is too slow. Can you give me some suggestion about this issue?

**Comment by speige** [comment]
I've updated npm with a new version that has a few fixes. Could you try the latest & see if it helps with your issue?

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
