### ISSUE TITLE
Loading in chunks docs incorrect for v0.4.5

### ISSUE THREAD

**Issue by bellizio** [rintoj/angular2-virtual-scroll#207]
With the most recent code change for __ChangeEvent__ noted in the [v0.4.4 changelog](https://github.com/rintoj/angular2-virtual-scroll/blob/master/CHANGELOG.md#v044), the code example for [loading in chunks](https://github.com/rintoj/angular2-virtual-scroll#loading-in-chunks) no longer works.

The following check needs updating:
```
if (event.end !== this.buffer.length) return;
```

In this case, the __*else*__ block will never execute because `event.end` will never equal `this.buffer.length` unless the check is updated to something like the following:
```
if (event.end + 1 !== this.buffer.length) return;
```
or
```
if (event.end !== this.buffer.length - 1) return;
```
---
I'm happy to open a PR with the changes to the README regarding this once there is feedback on the issue. Let me know!

**Comment by speige** [comment]
Good catch.

I like this version better:
if (event.end !== this.buffer.length - 1) return;

I'm away from my computer, so if you wouldn't mind doing a PR, I can merge it on my phone. Thanks.

**Comment by speige** [comment]
Actually. It's only a 1-liner. I think I can do it real quick. Save you the hassle of forking.

**Comment by speige** [comment]
Ok. This should be fixed now on github & npm. Thanks!

**Comment by bellizio** [comment]
@speige no problem! Thanks for the quick response and for your contributions to this project.

While I was at it, I was going to mention a minor typo I noticed in that section of the docs as well. But I will open a separate issue for it to be addressed there.
