### ISSUE TITLE
Typo in 'Loading in chunks' section

### ISSUE THREAD

**Issue by bellizio** [rintoj/angular2-virtual-scroll#208]
There is a small typo in the [Loading in chunks](https://github.com/rintoj/angular2-virtual-scroll#loading-in-chunks) section of the README:
```
import { ChangeEvent } from '@angular2-virtual-scroll';
```
should be: 
```
import { ChangeEvent } from 'angular2-virtual-scroll';
```

(without the @)

**Comment by speige** [comment]
Fixed in github. I won't publish to npm until the next version (unfortunately even for documentation changes you have to update the version #). Thanks.
