### ISSUE TITLE
Dependency issue with last version (0.4.7)

### ISSUE THREAD

**Issue by pcsantana** [rintoj/angular2-virtual-scroll#210]
Hi!
I tried to upgrade the lib version to the last one, but I got the follow error:

```
typescript: node_modules/angular2-virtual-scroll/dist/virtual-scroll.d.ts, line: 80
     Namespace ''*'' has no exported member 'Tween'.

      L79:  protected previousViewPort: IViewport;
      L80:  protected currentTween: tween.Tween;
      L81:  protected cachedItemsLength: number;
```

The tweenjs was installed successfully. 
Any advice to solve the issue?

Thank you.

**Comment by speige** [comment]
I just noticed package.json has tween setup strangely.

    "@types/tween.js": "^16.6.1", // this is invalid because version 1.0.0 is the latest
    "@tweenjs/tween.js": "^17.1.0"

Can you check if @types/tween.js was installed correctly in your node_modules?

You could try adding @types/tween.js to your package.json.

Since the compiled version of angular2-virtual-scroll is already included in npm I don't know why a consuming application would notice or care that the type definitions for tween.Tween weren't loaded correctly. My application uses angular2-virtual-scroll without including @types/tween.js in package.json & it works fine.

**Comment by pcsantana** [comment]
Thank you @speige!
Adding "@types/tween.js" to my package.json solved the problem!
I don't know why this happened. I tried too to initiate an ionic blank app and installed the plugin and everything worked as expected. Just in my working app occurred this errors.

**Comment by rafalmiler77** [comment]
@speige 
There is a difference between @types/tween.js (v like 16.9.0 ) and @types/tweenjs (v like 1.0.0)
so 
`"@types/tween.js": "^16.6.1"`
 is perfectly valid and the correct one.

**Comment by prashantagrawal17** [comment]
Guys, any updates on this issue??
i am still struggling with the same.
restarted IDE, install/Uninstall "ngx-virtual-scroll" multiple time but no luck.

Thanks in advance.

**Comment by speige** [comment]
I'm guessing it's something specific with your project, it seems to work fine for most people. Have you tried the suggestions in the above comments? Can you create a stackblitz or git repo reproducing the problem so we can help you troubleshoot?

**Comment by chabb** [comment]
if you have this line uncommented in `custom-typing.d.ts`, you'll get this error
// declare module '*';

**Comment by prashantagrawal17** [comment]
Thanks @speige, @chabb ,
I found something fishy in my project repository/configuration, as problem persist with my project configurations only.
I did created new ionic3/angular5 project and installed the plugin, it is working fine and not giving any compilation or run time error related to plugin.
Now i am looking into the project configuration files to resolve the problem.

**Comment by prashantagrawal17** [comment]
> I do not know exactly why it happens, but if this line is uncommented, typescript compiler will complain



> Thanks @speige, @chabb ,
> I found something fishy in my project repository/configuration, as problem persist with my project configurations only.
> I did created new ionic3/angular5 project and installed the plugin, it is working fine and not giving any compilation or run time error related to plugin.
> Now i am looking into the project configuration files to resolve the problem.

I tried the workaround and updated tsconfig.json with below code line
"typeRoots": ["node_modules/@types"],

After this, compilation error got resolved.

Configuration details are as below,

Ionic:
   ionic (Ionic CLI)  : 4.6.0 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:
   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 12 other plugins)

System:
   Android SDK Tools : 26.1.1 (D:\Softwares\adt-bundle-windows-x86_64-20140702\sdk)
   NodeJS            : v8.1.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 7

**Comment by aryehrein** [comment]
> "typeRoots": ["node_modules/@types"],

Full answer will be - in tsconfig.json ->
inside "compilerOptions" key add 
`"typeRoots": ["node_modules/@types"]`

This solved the problem for me

**Comment by speige** [comment]
I've re-arranged the publish format to prepare for ivy support. In the process I believe I may have fixed the tween issue. Can you re-test with the latest version on npm 2.0.4 ?
