### ISSUE TITLE
Q: Picking or selecting an item

### ISSUE THREAD

**Issue by dalu** [rintoj/angular2-virtual-scroll#211]
Hello,
I'm considering to use this lib as an image and file picker.

I have an article type that has image_id and audio_id fields.

Now in my edit-article component I'd like to have this virtual scroll for images, when there is no image picked.
Since there are like 2000 images and more I'd like to lazy fetch more, which is possible with this lib.

But can I also select an image by clicking on it? Is there a way of knowing if an element was clicked or is it possible to add a listener?

**Comment by speige** [comment]
Yes. Your code still renders the items, so you can add any angular events
you like, including (click). The control simply monitors for scroll events,
slices the array to the visible items, & sends them back to your code to
render.

**Comment by dalu** [comment]
Oh right, right.

```html
<virtual-scroll [items]="items" (update)="viewPortItems = $event">

    <my-custom-component *ngFor="let item of viewPortItems" (click)="returnThisItemId(item.id)">
    </my-custom-component>

</virtual-scroll>
```

Thanks alot :)
