### ISSUE TITLE
Is there a scroll end event? That only fires when scrolling is done?

### ISSUE THREAD

**Issue by thienedits** [rintoj/angular2-virtual-scroll#212]
I am using some ngIf statement to show a button, and since the current events fire multiple times, it causes button to "flicker".

**Comment by speige** [comment]
Closing this, since I'm confident it can be worked around with debounce & is more a user-specific issue rather than something wrong with the actual component.

**Comment by thienedits** [comment]
@speige ok will try the debounce, however since you use tween.js couldn't you use the onComplete to know when the animation finishes?

**Comment by speige** [comment]
Ok. Hopefully the debounce helps. Since you're using scrollToIndex you could also use the animationCompletedCallback parameter if you wanted to know when the tween has ended.
