### ISSUE TITLE
No overflow styles for parentScroll element in Internet Explorer

### ISSUE THREAD

**Issue by Eretik** [rintoj/angular2-virtual-scroll#218]
In case of using `parentScroll="window"` or `parentScroll="body"` overflow style do not appends to html/body element in IE as it appends in Chrome. As a result there are no vertical scoll bar in IE.
IE version: 11.611.16299.0.
IE Update version: 11.0.80
angular2-virtual-scroll version: 0.4.8

---
Workaround: add `overflow: auto` to body element. But I believe it should be fixed in component.

**Comment by speige** [comment]
I'm not able to reproduce this.

I tested in IE and it seems to work.
Navigate to http://rintoj.github.io/angular2-virtual-scroll & click parentScroll

Maybe a difference in our IE versions? Or something specific in your app code?
![image](https://user-images.githubusercontent.com/2002030/44166426-9b854900-a088-11e8-9d74-72b3fe3a3eee.png)

**Comment by speige** [comment]
Closing this. Please re-open if you think it's still an issue.

**Comment by Eretik** [comment]
It works on your demo page for my IE. And there are overflow styles for `html `element there too. It looks like my app specific issue. Gonna try to investigate it bit more.
