### ISSUE TITLE
On fast scroll items are not painted until the scroll stop

### ISSUE THREAD

**Issue by dario30186** [rintoj/angular2-virtual-scroll#219]
I have the virtual-scroll working in my Ionic app, but have encountered the following issue when scrolling on browser or android device:

1. Populate a large list of items (200+)
2. Scroll the list quickly, touching and releasing your finger on screen (i.e. a flicking motion)
3. List appears blank until the screen is touched again

It's really annoyig and a very bad user experience.
I see that in your demo http://rintoj.github.io/angular2-virtual-scroll/samples I can't reproduce the issue but I think that it depends on scroll speed. On your page the scroll is not so fast.

I don't know if it's a bug or just a limit of Angular. I would like that items were painted as fast as the scroll.
Do you have any suggestions ? Maybe I can decrease scroll speed ? It could be a solution for me.

NB even if I put just text without style for my items, then I always have the seme problem

**Comment by speige** [comment]
Unfortunately I don't have any ideas. It may be an app-specific issue since
others have not reported this. I'll need a stackblitz that shows this issue
occuring in order to help you troubleshoot.

**Comment by dario30186** [comment]
I will close this issue beacuse it is not related to this plugin but to ionic framework

**Comment by speige** [comment]
Good idea. I'll do that.
