### ISSUE TITLE
Possible to use ngx-perfect-scrollbar with this component?

### ISSUE THREAD

**Issue by aks1994** [rintoj/angular2-virtual-scroll#221]
Is it possible to use ngx-perfect-scrollbar with this component?

parentScroll prop only seems to take html elements/window. Is there any way I can tell virtual-scroll to use the scrollbar from ngx-perfect-scrollbar?

**Comment by speige** [comment]
I've never tried it, but in theory it should work with parentScroll.

```
<div class="ps" style="position: relative; max-width: 600px; max-height: 400px;" [perfectScrollbar]="config">
  <div>Scrollable content</div>
</div>
```

You'd want to assign parentScroll to the div.ps elemen

If you get it working, please create a simple demo so I can post your example code here on github for future users with this question.

Thanks.

**Comment by aks1994** [comment]
Thanks, appreciate the help but I'm not exactly sure how do I assign the parentScroll element.

I use perfect-scrollbar in component mode so it is:

```
<perfect-scrollbar>
      <virtual-scoll parentScroll="??">...</virtual-scroll>
</perfect-scrollbar>
```

<perfect-scrollbar> has a `<div class="ps">` element, but how do I pass this to parentScroll as this div does not have an Angular template ref attached to it.

Is there any syntax using css selectors that I can assign this div to parentScroll?

**Comment by speige** [comment]
You'll need to use the "directive usage" syntax instead.

```
<div class="ps" style="position: relative; max-width: 600px; max-height: 400px;" [perfectScrollbar]="config">
  <div>Scrollable content</div>
</div>
```

Documentation here: https://www.npmjs.com/package/ngx-perfect-scrollbar

Then you can use the angular # syntax to get a reference to that div.

**Comment by aks1994** [comment]
Thanks, that's perfect. I just had to add the following style to get it to work perfectly. What happened otherwise is that .scrollable-content which has height: 100% and max-height: 100vh gets computed height=100% of <virtual-scroll> and <virtual-scroll> in turn gets 100% of .ps-content which is the entire scrollable section. This left some whitespace at the end of the table due to 100vh being larger than the table. But the following style fixed the issue.

`virtual-scroll .scrollable-content{
	height: auto !important;
}`

**Comment by speige** [comment]
Closing this as the suggestion seems to have a resolved the issue. Please re-open if you continue to have problems.

**Comment by isNotOkay** [comment]
I got it working like this:

```
<div style="height: 300px;">
  <cdk-virtual-scroll-viewport itemSize="20" class="ps" perfectScrollbar style="height: 100%;">
    <table>
      <tr>
        <th>ID</th>
        <th>Item</th>
      </tr>
      <tr *cdkVirtualFor="let item of items; let i = index;">
        <td>{{i}}</td>
        <td>{{item}}</td>
      </tr>
    </table>
  </cdk-virtual-scroll-viewport>
</div>
```

**Comment by 2YY** [comment]
maybe you'll need overwrite  opacity `.ps__rail-x` and `.ps__rail-y` to `1`. it's set `0` in `@import '~perfect-scrollbar/css/perfect-scrollbar.css';`.
