### ISSUE TITLE
coming back from one tab to another giving a problem

### ISSUE THREAD

**Issue by mohammed534** [rintoj/angular2-virtual-scroll#222]
i have added 2 tables with 2 tabs with same scrollItems ...when i first load the data in the 1st tab it is working correctly but when i go to 2nd tab and coming back to 1st tab then only 1 element is showing in the DOM...is there any work around??

**Comment by speige** [comment]
My first guess would be to call the .refresh() api method of virtual-scroll when after the tab switch animation is completed.

If you can't get it working, a stackblitz would make it easier for us to help troubleshoot.

**Comment by speige** [comment]
Closing since I haven't heard back from the original poster & it seems like user error. Please re-open if you continue to experience issues.
