### ISSUE TITLE
no exported member "Tween'

### ISSUE THREAD

**Issue by rafalmiler77** [rintoj/angular2-virtual-scroll#227]
From testing stacktrace:
[at-loader] ./node_modules/angular2-virtual-scroll/dist/virtual-scroll.d.ts:97:35
    TS2694: Namespace ''*'' has no exported member 'Tween'.

**Comment by speige** [comment]
Duplicate of #210 

The proposed workaround in the other issue was to add
"@types/tween.js": "^16.6.1" to your apps package.json file

Can you verify if this fixes your issue? If so, please close this. Thanks.

**Comment by rafalmiler77** [comment]
It haven't worked unfortunately.  Installing "@types/tween.js": "^16.6.1"  throws still the same error.
My workaround was putting the typings from
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tween.js/index.d.ts
 into the custom typings file of the angular project.

**Comment by MoacirSchmidt** [comment]
For me the solution was:
Add to tsconfig.json file:
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types"
    ],

**Comment by indraraj26** [comment]
@rafalmiler77
in which files of angular you have pasted ?

**Comment by speige** [comment]
I've re-arranged the publish format to prepare for ivy support. In the process I believe I may have fixed the tween issue. Can you re-test with the latest version on npm 2.0.4 ?
