### ISSUE TITLE
no found in my project

### ISSUE THREAD

**Issue by gbelmm** [rintoj/angular2-virtual-scroll#23]
![captura de pantalla 2017-03-20 a las 13 35 02](https://cloud.githubusercontent.com/assets/731936/24110382/0bbd469c-0d72-11e7-95dc-aceb83036edf.png)

code:

  <virtual-scroll [items]="cards" (update)="scrollItems = $event" >
      <div  *ngFor="let card of scrollItems"  >{{card.dataevent.name}}</ div>
</ virtual-scroll>

data: from remote.

![captura de pantalla 2017-03-20 a las 13 36 50](https://cloud.githubusercontent.com/assets/731936/24110477/44c59390-0d72-11e7-8b26-e2ac5481fb67.png)

**Comment by istiti** [comment]
@gbelmm  please copy whole code example (css too) and retry

**Comment by matte00** [comment]
@gbelmm Is the virtual-scroll inside another element? 
` private calculateDimensions() {
    let el = this.element.nativeElement;
    let content = this.contentElementRef.nativeElement;
....
}`
return correct element?

**Comment by ManpreetSingh80** [comment]
<virtual-scroll style="display:block;height:100%" ..............................</virtual-scroll>
fixed it for me.

**Comment by gbelmm** [comment]
fix width style="display:block;height:100%"

 But I have 2 scroll
![captura de pantalla 2017-03-21 a las 17 03 40](https://cloud.githubusercontent.com/assets/731936/24168220/468245ac-0e58-11e7-8b06-03cfbd34657b.png)

**Comment by gbelmm** [comment]
If I remove the above it looks good but when scrolling up calls the refresh



![mar -21-2017 17-06-30](https://cloud.githubusercontent.com/assets/731936/24168392/c9b993b2-0e58-11e7-9d98-bc0f8a6a88c3.gif)

code

`<ion-content>

  <ion-refresher (ionRefresh)="doRefresh($event)">
     <ion-refresher-content></ion-refresher-content>
   </ion-refresher>


   
<virtual-scroll style="display:block;height:100%" [items]="cards" (update)="scrollItems = $event" >

<ion-item  *ngFor="let card of scrollItems" >




        <div class="img-box-host-b" style="border-bottom-right-radius:30px;">
          <lazy-img src="{{card.dataevent.event_images.firstimg_hq}}"></lazy-img>


           

           </div>


           <div class="item item-text-wrap">
              <div>
                 <div>
                    <span class="card-title">{{card.dataevent.name}}</span>
                 </div>
              </div>

              <div>
                 <div class="overflow">
                    <span class="card-subtitle">{{card.dataevent.subname}}</span>
                 </div>

              </div>
           </div>





</ion-item>
</virtual-scroll>


</ion-content>`

**Comment by ManpreetSingh80** [comment]
@gbelmm You can either substitute ion-refresher inside virtual-scroll to make it as a first element of list or instead of ion-refresher, use virtual-scroll built-in emitters of loading data in chunks.

**Comment by rintoj** [comment]
@gbelmm, I would suggest two things. 
1. Specify size for the container. It is essential for this component. 
2. As @ManpreetSingh80 suggested try using component's `start` and `end` events for loading data in chunks. `start` is fired when you are the beggning of the list and `end` when you are the bottom of the list.  [This documentation](https://github.com/rintoj/angular2-virtual-scroll#loading-in-chunk) should help you.
