### ISSUE TITLE
Header's cells are not UI aligned with body's cells

### ISSUE THREAD

**Issue by dheerendraiiita** [rintoj/angular2-virtual-scroll#230]
Hi,
I'm facing an issue on when using table when there is header ( fixed ) and body.
In this case, header's cells are not UI aligned with body's cells.

Could you help me?

<img width="1356" alt="issue" src="https://user-images.githubusercontent.com/25869745/44789173-8e547800-abb9-11e8-8770-471e077d3003.png">

**Comment by speige** [comment]
You'll need to create a stackblitz if you want help. I can't debug the issue without seeing the code.

However, here's an example that works with an HTML Table that you can copy from.
```
<virtual-scroll #scroll [items]="myItems">
	<table>
		<thead>
			<th>Index</th>
			<th>Name</th>
			<th>Gender</th>
			<th>Age</th>
			<th>Address</th>
		</thead>
		<tbody #container>
			<tr *ngFor="let item of scroll.viewPortItems">
				<td>{{item.index}}</td>
				<td>{{item.name}}</td>
				<td>{{item.gender}}</td>
				<td>{{item.age}}</td>
				<td>{{item.address}}</td>
			</tr>
		</tbody>
	</table>
</virtual-scroll>
```

Unfortunately, support for html tables with headers isn't perfect with virtual-scroll. The main issue is I don't know how to keep the header "fixed to top", I've tried a few techniques and none of them worked very well.

**Comment by speige** [comment]
I'm closing this since the example I posted should work. If you continue to have issues, please re-open.

**Comment by dheerendraiiita** [comment]
Thank you very much @speige for quick response. Your approach seems working.
