### ISSUE TITLE
angular6 suppport?

### ISSUE THREAD

**Issue by satyavanu** [rintoj/angular2-virtual-scroll#235]
The virtual scroll element supports angular6 ? i tried to add it , and it doesn't ?

**Comment by speige** [comment]
Yes, Angular 6 is supported. Please give more info on your issue, if you need more help.

**Comment by satyavanu** [comment]
i get the following errors

core.js:1598 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'virtual-scroll' is not a known element:
1. If 'virtual-scroll' is an Angular component, then verify that it is part of this module.
2. If 'virtual-scroll' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div>
    [ERROR ->]<virtual-scroll></virtual-scroll>


i already added that in the app.module.ts


and the template 


 <virtual-scroll #scroll [items]="items" (vsUpdate)="viewPortItems = $event">
        <div *ngFor="let list of items" class="custom">
             <p> {{list.name}} </p>
        </div>
    </virtual-scroll>


and ts contains


items = [{
     'name' : 'A',
     'id' : 1
  },{
     'name' : 'B',
     'id' : 13
  },{
     'name' : 'C',
     'id' : 11
  },{
     'name' : 'A',
     'id' : 1
  }];

**Comment by speige** [comment]
The error message seems self explanatory.

Most likely you're missing something from the intial setup instructions.

Either:
```
npm install angular2-virtual-scroll --save
```

or:
```
import { VirtualScrollModule } from 'angular2-virtual-scroll';
@NgModule({
    imports: [
        VirtualScrollModule
    ],
})
export class AppModule { }
```

Please paste your .module.ts file & package.json file.

Or, you could use https://stackblitz.com/ to reproduce your issue & send me the code.

**Comment by satyavanu** [comment]
i did this all,    @angular-redux/store": "9.0.0",
        "@angular/animations": "6.0.3",
        "@angular/cdk": "6.4.2",
        "@angular/common": "6.0.3",
        "@angular/compiler": "6.0.3",
        "@angular/core": "6.0.3",
        "@angular/flex-layout": "6.0.0-beta.17",
        "@angular/forms": "6.0.3",
        "@angular/http": "6.0.3",
        "@angular/platform-browser": "6.0.3",
        "@angular/platform-browser-dynamic": "6.0.3",
        "@angular/router": "6.0.3",
        "angular2-virtual-scroll": "^0.4.12",
        "core-js": "2.5.4",
        "ramda": "0.25.0",
        "redux": "4.0.0",
        "redux-logger": "3.0.1",
        "redux-observable": "1.0.0",
        "rxjs": "^6.2.2",
        "zone.js": "0.8.26"

and I was wondering then, it supports 6+

**Comment by speige** [comment]
Yes, it supports Angular 6.

It's probably an issue with your .module.ts file

Also, please double check that these files exists in your app (in case 'npm install' failed):
node_modules\angular2-virtual-scroll\dist\virtual-scroll.d.ts
node_modules\angular2-virtual-scroll\dist\virtual-scroll.js

**Comment by satyavanu** [comment]
<img width="274" alt="screen shot 2018-09-05 at 08 34 01" src="https://user-images.githubusercontent.com/3895610/45075162-7f545500-b0e6-11e8-97fd-bd07c2ddd729.png">

**Comment by speige** [comment]
npm install seems like it worked fine.

Probably your .module.ts

**Comment by satyavanu** [comment]
<img width="284" alt="screen shot 2018-09-05 at 08 36 07" src="https://user-images.githubusercontent.com/3895610/45075243-c5111d80-b0e6-11e8-82cf-27152d694891.png">
<img width="567" alt="screen shot 2018-09-05 at 08 35 44" src="https://user-images.githubusercontent.com/3895610/45075244-c6424a80-b0e6-11e8-9204-03eadcbfd297.png">

i don't see i did wrong in any step there ,

**Comment by speige** [comment]
Here's an example showing it working:
https://stackblitz.com/edit/angular-7lbtb6

I'm not sure what you're doing wrong, but maybe you can compare that side-by-side with your code, to find your mistake.
