### ISSUE TITLE
[Feature request] Events when the list is fully scrolled to top/bottom

### ISSUE THREAD

**Issue by Jahrenski** [rintoj/angular2-virtual-scroll#236]
Thanks for this virtual scroll lib, it works very well!

I have one feature request that would be very useful to us and probably others: events to fire when the user scrolled fully to the top and bottom of the lists.

The reason behind this is that we use virtual scroll along with a "pull to refresh" feature to force update the data. I have to disable the pull to refresh when the list is not fully scrolled to the top otherwise it will refresh every time you scroll the list which is not the intended behavior.

I tried simply using the vsStart event but it is not enough as the pull to refresh will be allowed as soon as the first item of the list is partly visible.

**Comment by speige** [comment]
This is a good idea. Are you willing to submit a pull request?

**Comment by speige** [comment]
I've coded this. It's not available on npm yet, but will be soon. Please read the updated documentation & let me know if you have any questions.

**Comment by speige** [comment]
This is now available on npm as version 0.4.13
Please re-open if this doesn't solve your issue.
