### ISSUE TITLE
Refresh Issues

### ISSUE THREAD

**Issue by matte00** [rintoj/angular2-virtual-scroll#24]
Hi mate,

i have an issue when change items insiede virtual-scroll. First time it's work ok, then i change the [items] collection with a new array of object but only two items are designed. I tried call refresh() method but it's don't work.

![issue](https://cloud.githubusercontent.com/assets/3216846/24145503/ac0f4086-0e31-11e7-89f0-61a0d0771b01.png)

The problem is in calculateItems() 
`   let indexByScrollTop = el.scrollTop / this.scrollHeight * d.itemCount / d.itemsPerRow;`

el.scrollTop is wrong. Have you any idea?

**Comment by rintoj** [comment]
@matte00, This issue was fixed with #22. Please make sure you are using the latest version, as of today it is 0.1.3.

**Comment by rintoj** [comment]
@ManpreetSingh80, please share more details about the issue with array update. I have done couple of updates the component recently. Please check those updates and if there are issues please revert.

**Comment by rintoj** [comment]
I have update the demo with two buttons to switch array at run time.

![image](https://cloud.githubusercontent.com/assets/10824903/24265709/6ec86784-102a-11e7-98ed-2752e85a4da1.png)

Please check the [demo page](http://rintoj.github.io/angular2-virtual-scroll/index.html)
