### ISSUE TITLE
angular2-virtual-scroll prevents horizontal browser scrollbar from working the ordinary way

### ISSUE THREAD

**Issue by PhilippSoehnlein** [rintoj/angular2-virtual-scroll#241]
I just got a (desktop only) app to maintain which uses angular2-virtual-scroll and applies something like `body { min-width: 1280px; } ` to ensure a certain minimum width. If the viewport is smaller than this, a horizontal scrollbar appears and most contents still align well and the horizontal scrollbar can be used to make the right part visible. Except the one's within the virtual scroll container, because of `.scrollable-content { max-width: 100vw; }`. They get cut and using the horizontal scrollbar just reveals more white space.

Is there a better way to prevent this behaviour other than to overwrite the `max-width` with something like the following?
```scss
virtual-scroll /deep/ .scrollable-content { 
    max-width: none;
}
```

Thanks for your help!

**Comment by speige** [comment]
If it fixes your issue, the CSS change you proposed should be fine. I'm not sure a better way to handle it.
