### ISSUE TITLE
NPM packaging: missing source file virtual-scroll.ts

### ISSUE THREAD

**Issue by petercmuc** [rintoj/angular2-virtual-scroll#26]
When including the npm module version 0.1.3 in my project I get an error:

> WARNING in ./~/angular2-virtual-scroll/dist/virtual-scroll.js
Cannot find source file '../src/virtual-scroll.ts': Error: Can't resolve **'../src/virtual-scroll.ts'** in '/home/name/dev/test/node_modules/angular2-virtual-scroll/dist'

The `dist` folder contains:
`virtual-scroll.d.ts`
`virtual-scroll.js`
`virtual-scroll.js.map`
`virtual-scroll.metadata.json`

The `src` folder containing `virtual-scroll.ts` is not contained in the `dist` folder.

**Comment by rintoj** [comment]
@petercmuc, npm package only contains distribution files. ie. the files compiled with ng-compiler. The original TypeScript files are excluded. I'm assuming you used the demo included in this repo where I directly refer to the TypeScript file, but it is only for the sake of the development. The module must always imported as 

```ts
import { VirtualScrollModule } from 'angular2-virtual-scroll'
```

**Comment by abel672** [comment]
@rintoj I had the same doubt due to this [post]([https://github.com/rintoj/angular2-virtual-scroll/issues/123]), where the author make test in his app and found in the issue in that file. Do you think that he downloaded all the demo to use it instead of npm manager?
