### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by nick-jonas** [rintoj/angular2-virtual-scroll#28]
Thank you for doing this!

Is it possible to do a horizontal scroll, something like [this](https://github.com/Corentinfardeau/horizontal-scroll) which uses VirtualScroll (non-angular)?

**Comment by rintoj** [comment]
@nick-jonas, thanks for your feedback. Horizontal scroll has been in my todos for a while. It's as difficult as doing the vertical scroll. I was just waiting for vertical scroll to be stable. I will do this, sure thing.

**Comment by Ammueliza** [comment]
@rintoj Thank you so much for this wonderful module!!
Actually I'm in need of the horizontal scroll. Do we have an implementation for horizontal scroll as well?
Thanks  in advance.....

**Comment by manju-reddys** [comment]
I have implemented both horizontal and vertical scroll but more efficient and no limits on the records. See the [plnkr](https://plnkr.co/edit/K0SSAxlLOfukNVAIcd3t?p=preview)

**Comment by VitaliyKotov** [comment]
@rintoj It seems that it's possible to add horizontal scroll by CSS rules only:
1. Set `overflow: auto` for virtual-scroll component (I just added a class to tag <virtual-scroll class="virtual-scroll">
2. Set the following rules to `.scrollable-content`: 
/deep/ .scrollable-content {
    display: inline-block;
    white-space: nowrap;
    width: initial !important;
}

**Comment by VitaliyKotov** [comment]
We faced the same issue in our app, and together with @codenough managed to add horizontal scroll with CSS styles only.
Set `overflow: auto;` to virtual scroll host element and 
/deep/ .scrollable-content {
       white-space: nowrap;
       min-width: 100%;
       width: initial !important;
  }

**Comment by speige** [comment]
This is now an officially supported feature of the component. Please update to the latest version on npm & try it. Closing issue. Please re-open if you have more problems.
