### ISSUE TITLE
Does it work with tables?

### ISSUE THREAD

**Issue by BogdanDumitruMarian** [rintoj/angular2-virtual-scroll#29]
Hi,

Your component looks great. I've tried it with lists and it does what it promises to.
However, I've tried using it for table rows, as you'll see below, but no rows are shown:

> <div class="table-responsive hidden-xs">
      <table class="table table-striped table-hover">
        <tr class="headerRow">
          <th *ngFor="let field of fields">{{field.label}}</th>
        </tr>
        <virtual-scroll [items]="data" (update)="viewPortItems = $event">
          <tr *ngFor="let entry of viewPortItems">
            <td *ngFor="let field of fields">
              <date-entry *ngIf="field.type === 'date'" [value]="entry[field.propertyName]" [format]="field.formatter" [filterTerm]="filterTerm"></date-entry>
              <string-entry *ngIf="field.type === 'string'" [value]="entry[field.propertyName]" [filterTerm]="filterTerm"></string-entry>
            </td>
          </tr>
        </virtual-scroll>
      </table>

**Comment by rintoj** [comment]
@BogdanDumitruMarian, Unfortunately this implementation will only work with tables without headers.

See below.

```html
   <virtual-scroll
      [items]="filteredList"
      [childHeight]="43"
      (update)="scrollItems = $event"
      (change)="indices = $event">
      <table>
        <tr *ngFor="let item of scrollItems">
          <td>{{item.index}}</td>
          <td>{{item.name}}</td>
          <td>{{item.gender}}</td>
          <td>{{item.age}}</td>
          <td>{{item.address}}</td>
        </tr>
      </table>
    </virtual-scroll>
```
