### ISSUE TITLE
Error in list item

### ISSUE THREAD

**Issue by shaitya** [rintoj/angular2-virtual-scroll#3]
Can't bind to 'item' since it isn't a known property of 'list-item'.
1. If 'list-item' is an Angular component and it has 'item' input, then verify that it is part of this module.

**Comment by rintoj** [comment]
'list-item' must a custom build angular2 component, outside of this library. A sample list item is give below or check the [demo app](https://github.com/rintoj/angular2-virtual-scroll/tree/master/demo) for [list-item.component.ts](https://github.com/rintoj/angular2-virtual-scroll/blob/master/demo/src/app/lists/list-item.component.ts)

```
import { Component, Input } from '@angular/core';

export interface ListItem {
    index?: number;
    name?: string;
    gender?: string;
    age?: number;
    email?: string;
    phone?: string;
    address?: string;
}

@Component({
    selector: 'list-item',
    template: `
        <div class="avatar">{{item.index}}</div>
        <div class="item-content">
            <div class="name">{{item.name}}</div>
            <div>
                <span class="badge">{{item.age}} / {{item.gender}}</span>
                <span>{{item.email}} | {{item.phone}}</span>
            </div>
            <div>{{item.address}}</div>
        </div>
    `,
    styleUrls: ['./list-item.scss']
})
export class ListItemComponent {
    @Input()
    item: ListItem;
}
```

**Comment by shaitya** [comment]
What if we want to achieve this using div tag???

**Comment by shaitya** [comment]
Got it . Please include what the list-item in the documentation so that there is no confusion. Thanks

**Comment by rintoj** [comment]
I have added to this to documentation. Thanks for bringing this to my notice.

Yes, you could also use a div tag if you like to do so.

```
<virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <div *ngFor="let item of viewPortItems" [item]="item">{{ item }}</div>
</virtual-scroll>
```

```
let items[] = ['Item1', 'Item2'];
```

**Comment by shaitya** [comment]
If we give  <div *ngFor="let item of viewPortItems" [item]="item">{{ item }}</div>
we will still get the following error 
                        "Can't bind to 'item' since it isn't a known property of 'div'. "
so simply <div *ngFor="let item of viewPortItems">{{item}} </div> is enough. This worked for me

**Comment by cuongnm265** [comment]
@rintoj Hi, I did what you mentin below and it still doesn't work. I tried to move (update) expression to another method in my .ts file but it seem my app can't reach the update event
