### ISSUE TITLE
Scroll is glitchy on iOS safari (Ionic 2)

### ISSUE THREAD

**Issue by mthahzan** [rintoj/angular2-virtual-scroll#30]
I'm using this library as part of an Ionic 2 application. When running on an iOS device, we saw the below glitchy behavior.

![Glitch on iOS safari](https://media.giphy.com/media/tPvtkRl0KcypG/giphy.gif)

This is the template.

```
<virtual-scroll
    [items]="recipes"
    (change)="indices = $event"
    (update)="scrollItems = $event"
    style="height: 100%; display: block">
    <div *ngFor="let item of scrollItems" style="width: 100%">
      ...
    </div>
</virtual-scroll>
```

The used `recipes` variable starts out as an empty array and is updated after the API request observable is completed.

**EDIT**

Tried again with a much simpler content

```
  <virtual-scroll
    [items]="testItems"
    (change)="indices = $event"
    (update)="scrollItems = $event"
    style="height: 100%; display: block">
    <div *ngFor="let item of scrollItems" style="width: 100%">
      <ion-card style="height: 300px; width: 100%">
        <p>Item</p>
      </ion-card>
    </div>
  </virtual-scroll>
```

Still the problem is there.

**Comment by smoku** [comment]
@mthahzan it is bug related to UIWebView, try WKWebView - http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by omaxlive** [comment]
Installing this plugin fixes the issue: [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview )
because of WKWebView!:)
