### ISSUE TITLE
No scrolling when adding items at the beginning

### ISSUE THREAD

**Issue by PeterBurner** [rintoj/angular2-virtual-scroll#31]
I'm trying to write a chat application with this library.
Unlike normal lists I have to add items to the beginning of the input array. I used the `start` event to trigger this update.
The problem is that the scroll view automatically scrolls to the top then. Which in turn triggers the `start` event again and so on.
Could you add a parameter to prevent this scrolling to top or give an example how to achieve the wanted behavior with the current release?
I already tried to use the `scrollInto` function after updating the input array but for some reason I created an infinite rendering loop.

**Comment by ManpreetSingh80** [comment]
A simple hack would be adding some delay in start event to prevent nested triggering of start event. You can compensate the delay by adding some loading animation.

**Comment by PeterBurner** [comment]
Hi @ManpreetSingh80 
Thanks for your response.
Unfortunately it does not help.
If I add a delay to the start event the list still scrolls to the top after the items are inserted. They are simply inserted with a delay now.
I think this scrolling to top is the default angular behaviour since the whole list is rerendered.
ngFor behaves the same way

**Comment by ManpreetSingh80** [comment]
@PeterBurner Can you provide a plunker? It will be more helpful to debug.

**Comment by PeterBurner** [comment]
sure

without delay:
https://embed.plnkr.co/tOElYeJhvtvGrOIsR2Z9/
with delay:
https://embed.plnkr.co/92lhL9CS8LCYoOSE3Ze7/

as you see in both examples the list automatically scrolls to top after I insert new Items at the beginning
I want it to keep the previous beginning of the list in focus

**Comment by ManpreetSingh80** [comment]
@PeterBurner There you go
[https://plnkr.co/edit/8x72FqXnWOL5oyzQNIWm?p=preview](https://plnkr.co/edit/8x72FqXnWOL5oyzQNIWm?p=preview)

**Comment by PeterBurner** [comment]
You stopped it from loading further data.
That's not what I had in mind.
I wanted the list not to scroll.
In other words, the current viewport should not move. Only the scroll bar should adapt to the new container height.

**Comment by ManpreetSingh80** [comment]
@PeterBurner I don't think it is possible with current implementation of this virtual-scroll. But you can modify it suit your needs.

**Comment by PeterBurner** [comment]
I thought so
that's why I created an issue here instead of asking on stackoverflow

**Comment by rintoj** [comment]
@PeterBurner, I just fixed #39 - infinite loop issue. Could you check again if you still face this problem. If yes, please reopen this issue. Also see my comments on #37

**Comment by pcsantana** [comment]
@PeterBurner did you find a solution? I have the same issue. When I add items at the beginning, the viewport items replaced by the new items I just added. 
The desired behavior is to keep the current viewport items, and just grow the scroll height above it.
Thanks!

**Comment by PeterBurner** [comment]
hi @pcsantana
not really
I found a hacky solution by manually resetting the scroll position after scrolling to the top within the ngAfterViewChecked but that's definitely not something one should use in productive code since it doesn't really perform well
sorry

**Comment by shajeeck** [comment]
@PeterBurner @pcsantana any better solution found for this issue? to keep the scroll position when items are added to the top of list?

**Comment by PeterBurner** [comment]
no
sorry
