### ISSUE TITLE
requestAnimationFrame?

### ISSUE THREAD

**Issue by DaveMBush** [rintoj/angular2-virtual-scroll#33]
I was under the impression that angular handles updates so we shouldn't need requestAnimationFrame.

I only noticed this because I use JSDOM to run my tests and the polyfill for this is not included in standard Angular CLI stuff.  Also, I think the use of this is causing flicker and taking it out will remove that.

**Comment by rintoj** [comment]
@DaveMBush, I didn't want to block browser's UI thread while doing scroll calculations. In my tests, I found not using requestAnimationFrame makes browser freeze at some conditions.

**Comment by DaveMBush** [comment]
@rintoj yeah, I finally figured that out.  That's why I closed it.
