### ISSUE TITLE
UNMET PEER DEPENDENCY @ionic-native/core@3.4.4 invalid on npm install

### ISSUE THREAD

**Issue by Natanael1234** [rintoj/angular2-virtual-scroll#36]
I'm using Ionic 2.3. When I try to install this library I get this message:

corp-now@ E:\Projetos\Ionic2\CorpNow
+-- UNMET PEER DEPENDENCY @ionic-native/core@3.4.4 invalid
`-- angular2-virtual-scroll@0.1.5

How could I solve this?

**Comment by ManpreetSingh80** [comment]
Its an Ionic issue and it seems you have already [solved](http://stackoverflow.com/questions/43358473/unmet-peer-dependency-ionic-native-core3-4-4-invalid-on-install-angular2-virtu) this. So please close this issue.
