### ISSUE TITLE
How do I calculate index inside *ngFor now?

### ISSUE THREAD

**Issue by pfalcon64** [rintoj/angular2-virtual-scroll#365]
Before switching to an infinite scroll, my ngfor used to look like:

*ngFor="let row of GridData; let index = index;"

I need index because some methods I want to call from the grid rows need to act on rows adjacent to the selected one - so i pass the index as a parameter in the click event. This is no longer possible with this component because index is relative to just the viewport items - not the whole list.

**Comment by ShakesVision** [comment]
For reference, the index of the first element can be used with ngFor index to display correct item indices.

In ts:
```
startIndex:number;
vsChange(ev) {
    this.startIndex = ev.startIndex;
}
```

In HTML:
```
<div *ngFor="let r of scroll.viewPortItems;let i=index"> 
    {{i+1+startIndex}} 
</div>
```
