### ISSUE TITLE
Need help/suggestion: "bottom-up direction"

### ISSUE THREAD

**Issue by OClement** [rintoj/angular2-virtual-scroll#37]
Hi,

The component seems to work just fine in normal situations where a list is displayed from top to bottom; However, in my use case, I need to flip the whole thing; Think of a chat, where the first message is at the top, and last is at the bottom (which means the scrollbar needs to stay at the bottom too)

I iterate over my collection normally and planned to use Flexbox to reorder the messages on the screen. Obviously, the VS component isn't aware of that and all sort of weird things happens

One "crazy" solution I though about was to use CSS transform to rotate the whole container 180deg, then each repeated item 180deg as well; That probably would work but then the mouse scroll direction would also be upside down...

I'm still trying to figure out a simple solution but haven't got around anything yet. Maybe someone will have an idea about this?

Thanks

**Comment by rintoj** [comment]
@OClement, I don't see a problem implementing a chat like behaviour: display the chats in the same order as they arrive and keep the scroll position to the bottom. The component's `scrollInto(item)` api can be used for focusing on the last message. One more thing: make sure the `items` array is immutable. Any operation you do on this array must produce a new array.

**Comment by rintoj** [comment]
@OClement , please feel free to reopen this issue if my suggestion hasn't worked for you.

**Comment by OClement** [comment]
Thanks for the suggestion
I'll look into it this week

The array is indeed immutable

O.
