### ISSUE TITLE
Safari Issue

### ISSUE THREAD

**Issue by amirsaber** [rintoj/angular2-virtual-scroll#41]
In safari, when scrolling all the way up, it only shows two items out of many and then by scrolling a little bit back it suddenly pops all of them.
I had a look I noticed two things on safari:
1. scrollable content translate goes to -440
2. height of the virtual-scroll element it self changes when I scroll all the way up

**Comment by amirsaber** [comment]
it seems if we add
```javascript
        if(el.scrollTop<0){
            el.scrollTop = 0;
        }
```
before [line 161](https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L161) will do the job. It's actually because of negative number for bounce scrolling in safari.

**Comment by rintoj** [comment]
@amirsaber, thanks for pointing out the issue. This is fixed and will be available in the next version.
