### ISSUE TITLE
Scrolling performance can be improved with switchMap

### ISSUE THREAD

**Issue by awormasi** [rintoj/angular2-virtual-scroll#43]
I noticed that in lists with a large number of items rendered, scrolling up and down repeatedly causes chrome to become temporarily unresponsive when the user stops scrolling. During this time the memory also temporarily spikes. I think this is because chrome is busy garbage collecting all the rendered dom elements that were removed from the previous scroll events. 

To improve performane, you can replace the following line in ngOnInit:

`this.onScrollListener = this.renderer.listen(this.elRef.nativeElement, 'scroll', this.refresh.bind(this));`

with the following:

```
scroll$: Subject<Event> = new Subject<Event>();
@HostListener('scroll')
onScroll(e: Event) {
    this.scroll$.next();
  }

ngOnInit() {
    this.scroll$.switchMap(() => {
      this.refresh();
      return Observable.of();
    }).subscribe(() => {});
    // other code ...
}
```

With this change, the rendering of items from previous scroll events gets canceled and chrome stays responsive and the memory stays constant.

**Comment by rintoj** [comment]
@awormasi, thanks for your help. Your solution works amazingly well. I will publish it with the next version.
