### ISSUE TITLE
Can´t get it to work properly using Materials (md-card) and FlexLayout

### ISSUE THREAD

**Issue by mackelito** [rintoj/angular2-virtual-scroll#47]
![2017-05-15 22_25_29](https://cloud.githubusercontent.com/assets/598463/26077736/7104c076-39bd-11e7-87c9-8c9ead071c92.gif)
Not sure what´s going on here :)

**Comment by rintoj** [comment]
@mackelito, can you share the code?

**Comment by mackelito** [comment]
ended up not using a virtual scroll at all :P
