### ISSUE TITLE
Sticky subheader with virtual scroll

### ISSUE THREAD

**Issue by WhatzzUp** [rintoj/angular2-virtual-scroll#48]
Hello folks,

is somethins like this possible : https://codepen.io/chrissp26/pen/gBrdo

I try to implement a "sticky" subheader with your virtual scroll. Acutally i failed ... :(

Cheers

Chris

**Comment by rintoj** [comment]
@WhatzzUp, Sorry that's something not possible with the current implementation. I have had people asking about doing a table with fixed header, that's not possible either. I have been thinking about another approach to solve this. Please watch this repo, I may have an update to this problem.

**Comment by istiti** [comment]
@rintoj whatsup, issue is closed do you find solution here ? maybe just before ngFor loop  we could have(here squelette):

```
<div ... virtualScoll ... >
<div class=sticky>my stickybar</div>
<div *ngFor=virtualPort>...</div>
</div>
```

and just add to .sticky class the transform css property like in .scrollable-content but decrementing so if:
`class="scrollable-content" style="transform: translateY(595px);"`
the .sticky should have  `style="transform: translateY(-595px);"`

maybe  problem is we don't have current item

**Comment by isabelanazare** [comment]
In the latest version you can use #header for the header to be fixed at the top.
