### ISSUE TITLE
Scroll to item

### ISSUE THREAD

**Issue by uso5** [rintoj/angular2-virtual-scroll#49]
Hi

I implemented virtual scroll to my project, it work perfectly. How can I scroll to certain item? Lets say i have sorted contact list and i need to jump to items by alphabet.

Thanks.

**Comment by rintoj** [comment]
@uso5, please see https://github.com/rintoj/angular2-virtual-scroll#focus-on-an-item

**Comment by rintoj** [comment]
Please see. https://github.com/rintoj/angular2-virtual-scroll#focus-on-an-item
