### ISSUE TITLE
No items are shown

### ISSUE THREAD

**Issue by farin99** [rintoj/angular2-virtual-scroll#5]
Hi, there seems to be an issue that is causing the virtual-scroll calculation to fail.
See attached image. There are only 12 items in the full list, and each item height is around 38px. however the scrollbar-content has a translateY=632px, which is causing it to render nothing.
I'm not sure if it is related, seems to reproduce with small amount of items.

This is an awesome component 👍. However, with the current bug I'm a bit worried to use it in production :(

![image](https://cloud.githubusercontent.com/assets/683343/20794997/b032b004-b7d7-11e6-849a-94054be8dcef.png)

**Comment by rintoj** [comment]
From what I see, I think the problem is with container size. If the container size changes virtual scroll needs to be made aware explicitly. If you are trying to include virtual scroll in a dropdown, call `refresh()` function after opening the dropdown (include time for animation as well). That should fix. Let me know how it goes. If problem persist, please share the code I can have a look at it.

```
import { Component, ViewChild } from '@angular/core';
import { VirtualScrollComponent } from 'angular2-virtual-scroll';

@Component({
    selector: 'rj-list',
    template: `
        <virtual-scroll [items]="items" (update)="scrollList = $event">
            <div *ngFor="let item of scrollList; let i = index"> {{i}}: {{item}} </div>
        </virtual-scroll>
    `
})
export class DesignWorkspaceComponent {

    protected items = ['Item1', 'Item2', 'Item3'];

    @ViewChild(VirtualScrollComponent)
    private virtualScroll: VirtualScrollComponent;

    afterOpen() {
        this.virtualScroll.refresh();
    }
}
```

**Comment by farin99** [comment]
Thanks for the quick response! I don't think my container height is changing. However, I'm animating the container width. I'll try to remove the animation and see if the bug still reproduce.

**Comment by rintoj** [comment]
Well, I am almost sure bug will still exist even after animation is removed. The component takes height and width (for multi column support) into consideration for calculating number of items. If container size changes (with or without animation) call **refresh()**

**Comment by rintoj** [comment]
I guess this is the way to go until [Resize Observer](https://wicg.github.io/ResizeObserver/) is fully implemented.

**Comment by farin99** [comment]
The issue is related to having elements with different heights in the viewport.
it isn't related to resizing and will happen even if the container size never changes.
