### ISSUE TITLE
Focusing element from top

### ISSUE THREAD

**Issue by uso5** [rintoj/angular2-virtual-scroll#50]
Hi thanks updating docs for focusing on element. Function is handy, but it focusing on element at bottom of screen, I am talking about  [this line](https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L145)

`this.element.nativeElement.scrollTop = Math.floor(index / d.itemsPerRow) *
      d.childHeight - Math.max(0, (d.itemsPerCol - 1)) * d.childHeight;`

originally it should scroll to top of the item (correct me if i am wrong): 

`this.element.nativeElement.scrollTop = Math.floor(index / d.itemsPerRow) * d.childHeight;`

Thanks for an answer.

**Comment by rintoj** [comment]
Hi, ideally it must place the element at the top of the list, except if there are no more items to fill the reset of the viewport. So I'm assuming that the element is placed at the bottom because it is the last element in the list. Please confirm.

**Comment by uso5** [comment]
Hi @rintoj, I prepared plnkr -> https://plnkr.co/edit/Os1D8M14bFoW9pZHDj4Y?p=preview

When you click on Jump to button, desired item is scrolled on the bottom of the content. It should scroll the item on the top of the content. That is my desired behaviour. My solution is suggested in previous comment.

**Comment by rintoj** [comment]
Ok got it. thanks for plnkr. This needs a fix.

**Comment by uso5** [comment]
Hi @rintoj if you are still working on this issue, I want to just remind you, that I made fix right above :) Thanks.
