### ISSUE TITLE
Can I use the virtual scroll with a HTML table?

### ISSUE THREAD

**Issue by mahcr** [rintoj/angular2-virtual-scroll#51]
Is there any way to use this component with a table?

Something similar to:
```
    <virtual-scroll [items]="rows" [childHeight]="30">
      <tr *ngFor="let item of rows">
        <td>Some text</td>
      </tr>
    </virtual-scroll>
```

**Comment by mahcr** [comment]
I was able to make it work with a table following the demo in the repo. But I seems It does not work well if a thead and th tags are included

**Comment by SlapBassist** [comment]
I'm trying to get this component to work with div based tables and having a heck of a time. Has anyone else run into this use case?

**Comment by Mohendran** [comment]
Me too... I cant get the viewPortItems when I use virtual scroll

**Comment by evandocarmo** [comment]
Same here. No news?

**Comment by Mohendran** [comment]
I think the solution for this is to use virtualScroll directive

```
<table>
<tr>
<th>No</th>
<th>Name</th>
</tr>
<tbody virtualScroll [items]="items" (update)="viewPortItems = $event">
<tr *ngFor="let item of viewPortItems">
<td>{{item.No}}</td>
<td>{{item.Name}}</td>
</tr>
</table>
```

**Comment by MrToasty97** [comment]
I'm getting "Can't bind to 'items' since it isn't a known property of 'tbody'." Error,

**Comment by mahcr** [comment]
@Mohendran doesn't work for me. <tr>'s are overlapping the thead

**Comment by Mohendran** [comment]
@mahcr  Can U attach a screenshot and a snippet of ur code?

**Comment by MastaBleh** [comment]
Get over the form of this message, but this discussion is loosing time & efforts of way too much people.
Does anybody here as ever spent 5min to gather some informations ? God, its working, this discussion is bullshit. Only to say LOVE YOU all, i'll spend 7min registering and writting this.
Whats fed me up ? I got of course the same problem of you all but i simply did not stop at the first "its not working" comment... 

What we want? simply the benefits of html table characteristics unstead of spending time to refactor all design into self managed div blocks. (also: the scrollbar in the tbody block, keep thoses th headers visible).
The problem: html table are strict in the dom construction.
note: elements involved with overflow property, in complex design could interfere, care.


**Directive:**
@MrToasty97 Angular2-virtual-scroll directive is working out of the box. 
c'ant bind to 'items'; directive is called 'virtualScroll' and not 'virtual-scroll'.
see demo/usage 3rd snippet : 
```
<div virtualScroll [items]="items" (update)="viewPortItems = $event">
    <list-item *ngFor="let item of viewPortItems" [item]="item">
    </list-item>
</div>
```

**Using directive in tbody context: not working**
<table>
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody virtualScroll [items]="items" (update)="viewPortItems = $event">
    <tr *ngFor="let item of viewPortItems">
      <td>{{item.No}}</td>
      <td>{{item.Name}}</td>
    </tr>
  </tbody>
</table>

Implemented a2 virtual scroll in various context without problem (as directive or component), never managed to get the scroll working as expected in the described configuration.
always as 1 of the following problem:
- all items are visible
- cant scroll at all
- only 2 element visible when 20 are expected to be visible

**Here is the 10M$ working snippet**
```
<table>
    <thead>
        <tr>
            <th>col1</th>
            <th>col2</th>
            <th>col3</th>
        </tr>
    </thead>
    <virtual-scroll [items]="placeHolders" (update)="visibleElements = $event" style="height: calc(100vh - 4.2rem - 4.2rem - 4.2rem + 1.29rem);" [childHeight]="46">
        <tbody>
            <tr *ngFor="let element of visibleElements; let i=index">
                <td>index {{i}}</td>
                <td>{{element}}</td>
                <td></td>
            </tr>
        </tbody>
    </virtual-scroll>
</table>
```

Key points: 
- <tbody> inside virtual scroll selector
- tbody styled as height: calc(100vh - 4.2rem - 4.2rem - 4.2rem + 1.29rem); display: block;
- give the same height to the virtualscroll comp : style="height: calc(100vh - 4.2rem - 4.2rem - 4.2rem + 1.29rem);". Do not give fixed value on both (tbody+virtualScroll) or you ll get stuck when the user resize the windows. With calc( 100vh - Xrem + Xrem) you got your responsive and no unexpected scrollfkingbar.
- specify the childHeight in px

Its working. (if not, i'll be fed from your tears and might spend 2min to get it working to you and another 30min finding some esthetic way of rubbing your head in your shit.).

And for very large list (when you want to mind fuck your users or when you cant ask 10K+ object to your api), use this component for with "proxy" binding.
(in comp.ts)
this.placeHolders: number[] = Array.from(Array(10000).keys()); -> generate [0,1,...,10000]
and in 
set visibleElements(value: any[]) {
        console.log(value); //ex: print: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
        // get elements 18 to 36 from your api
        this.visibleElements$ = value;
    }


Thank you Rinto Jose, it's appreciated that you spent some time giving us this virtual scroll.
Fuck you people with the art of saying bullshits without the capacities to evaluate the consequences of misinformation.

**Comment by MastaBleh** [comment]
content of answer : okay
form of answer: jerk

everybody agreed, so get focused on content.

**Comment by MastaBleh** [comment]
Okay, so the use case i reduced to "proxy binding" is in fact more complex than expected.

**-> the goal is to handle a large amount of item with a decent performance**
_Keep in mind that the first thing to point out is the business need behind, this is a technical implementation relaying on various specific constraints. You need to challenge WHY do you need a such large amount of object, does it make sense to the user to be able to scroll in 10k+ objects. In 90+% of case, the answer is no. And simpler implementation of virtualScroll perfectly fit your needs._
**-> I'll probably make a demo and post it here, in the following days**

If you want to build a virtual scroll on a large amount of object ( 10k+ placeholders ) with 20 items visible in a tbody
- with expected HTML table behavior
- cant ask on a decent timing (<200ms more than 30 items )
- cant ddos my WebApi (use of a call stack on visibleElements) load elements from WebApi only when scroll end
- with filters on items (that will update the placeolders quantity )
- with fast transistion between the placeholder displaying a row with 'loading...' and the displayed item with appropriate td
- with natural-like scroll behavior (i want my item tightly binded to the placeholder, i can't handle to see a scroll effect with the same item on the same indexed row for a millisecond, i killed babies to survive that)

**Comment by maikolestevez** [comment]
Hello  @MastaBleh,
I'm trying to use your suggestions, but i'm not getting good results.

This is my html
```
    <virtual-scroll [items]="filteredList" (update)="viewPortItems = $event" style="height: calc(100vh - 4.2rem - 4.2rem - 4.2rem + 1.29rem);" [childHeight]="46">
                    <tbody id="tbody-envios">
                        <tr *ngFor="let data of viewPortItems">
                            <td>{{envio.name}}</td>
                            <td>{{envio.email}}</td>
                            <td>{{envio.sendDateTime|date:'dd/MM/yyyy hh:mm:ss'}}</td>
                            <td>{{envio.campaignStatus}} </td>
                            <td [class]="envio.bounce?'red-text':'blue-text'">{{envio.bounce?'Rechazado':'No Rechazado'}}</td>
                            <td [class]="envio.click?'blue-text':'red-text'">{{envio.click?'Archivo Abierto':'No Abierto'}}</td>
                            <td class="file-download" (click)="downloadFile(envio)">{{envio.tipoArchivo==1?'data1':'data 2'}}</td>
                        </tr>
                    </tbody>

                </virtual-scroll>
```
Css
```
virtual-scroll {
    display: block;
    width: 100%;
}
#tbody-envios {
    height: calc(100vh - 4.2rem - 4.2rem - 4.2rem + 1.29rem);
    display: block;
}
```
I have followed your tips but what i'm getting is this
![gitimage](https://user-images.githubusercontent.com/8959257/35197711-bb1e6592-feb9-11e7-8fa8-5e75f2ed3acb.PNG)

**Comment by yusijs** [comment]
Got scroll working with the directive on a tbody element \o/

Feels rather hacky using flex to get it working. (I was having the exact same issue as @maikolestevez where the width would never be correct).

css and html below (the height attribute is an input for my table component) - hopefully this helps whoever else stumbles in here :) 

```css
virtual-scroll {
  display: block;
  width: 100%;
}

table {
  border-collapse: collapse;
  border-spacing: 0;
 
  
  text-align: left;
  
   display: flex;
  flex-flow: column;
  width: 100%;
}

thead {
  flex: 0 0 auto;
  width: 100%;
}

tbody {
  width: 100%;
      /* body takes all the remaining available space */
  flex: 1 1 auto;
  display: block;
  overflow-y: scroll;
}


table tbody tr {
  width: 100%;
}
table thead,
table tbody tr {
  display: table;
  table-layout: fixed;
}
```

```html
<table class="mdl-data-table  mdl-shadow--2dp" [style.height]="height + 'px'">
    <thead style="border-bottom: 1px solid rgba(0, 0, 0, 0.12)">
        <tr>
            <th *ngFor="let col of columns; let i = index" [class.mdl-data-table__cell--non-numeric]="!col.numeric" [ngClass]="col.headerClass">
                {{ col.label }}
            </th>
        </tr>
    </thead>
    <tbody [style.height]="(height - 50) + 'px'" virtualScroll [items]="rows" (update)="scrollItems = $event">
            <tr *ngFor="let row of scrollItems">
                    <td *ngFor="let col of columns; let i = index"
                    [class.mdl-data-table__cell--non-numeric]="!col.numeric" [ngClass]="col.headerClass">
                        {{ row[col.prop] }}
                    </td>
                </tr>
    </tbody>
</table>
```

**Comment by speige** [comment]
Closing this as there are working solutions posted. If anyone has suggestions to make this easier, feel free to submit a pull request. Thanks.

**Comment by mahcr** [comment]
@speige - I would suggest not to close this ticket. This still a bug and the work arounds are very hacky.

**Comment by speige** [comment]
@mahcr 
I'm not personally using it with HTML table, so I'm not sure what the complaint is. However, I do know there are working solutions.

There is an example with HTML Table at http://rintoj.github.io/angular2-virtual-scroll/samples

Can you explain why the workarounds are hacky & not good enough & do you have any suggestions on a better approach?

**Comment by speige** [comment]
@mahcr ok, so I played around with tables & I agree with you, the workarounds are hacky. I'll re-open this until we have a better solution.

**Comment by speige** [comment]
Let me clarify. The *only* part I think is hacky is if you need a fixed <thead> at the top of the scroll area. I don't know a solid solution for that. Everything else seems okay.

In my opinion this is the best way to use an HTML table with virtual-scroll:
```
<virtual-scroll #scroll [items]="myItems">
	<table>
		<tbody #container>
			<tr *ngFor="let item of scroll.viewPortItems">
				<td>{{item.index}}</td>
				<td>{{item.name}}</td>
				<td>{{item.gender}}</td>
				<td>{{item.age}}</td>
				<td>{{item.address}}</td>
			</tr>
		</tbody>
	</table>
</virtual-scroll>
```

You can also add a header (not-fixed) if desired:
```
<virtual-scroll #scroll [items]="myItems">
	<table>
		<thead>
			<th>Index</th>
			<th>Name</th>
			<th>Gender</th>
			<th>Age</th>
			<th>Address</th>
		</thead>
		<tbody #container>
			<tr *ngFor="let item of scroll.viewPortItems">
				<td>{{item.index}}</td>
				<td>{{item.name}}</td>
				<td>{{item.gender}}</td>
				<td>{{item.age}}</td>
				<td>{{item.address}}</td>
			</tr>
		</tbody>
	</table>
</virtual-scroll>
```

Obviously virtual-scroll needs a fixed width/height as in other virtual-scroll examples.

The tbody #container is necessary so virtual-scroll knows how to calculate the childHeight items correctly. Otherwise the browser auto-generates a tbody in the DOM, but virtual-scroll thinks table is the container, so it auto-calculates childHeight off tbody instead of tr. (Notice I didn't have to specify childHeight because tbody #container allows the auto-calculate to work correctly)

Unfortunately, the header will scroll out of view. I think most users would preferr it fixed to top of scroll area. This *could* be done by modifying the source to remove these line from getElementsOffset:
```
		if (this.containerElementRef && this.containerElementRef.nativeElement) {
			offset += this.containerElementRef.nativeElement[this._offsetType];
		}
```
However, the header will be randomly off by a few pixels as you scroll which makes it feel jumpy. I think it's better to let the header scroll out of the viewport rather than keeping it fixed to top but jumpy.

**Comment by speige** [comment]
I've decided to close this. The only issue I'm aware of is that you can't do a fixed-to-top-header. I'm creating a separate feature request for that. #237
