### ISSUE TITLE
Loading rows after loaded 0 rows

### ISSUE THREAD

**Issue by pedrollanes** [rintoj/angular2-virtual-scroll#53]
I have a virtual scroll that is working fine but when the filter reduce the list to 0 elements, next time I change the source list to a list with elements, the virtual scroll only show 2 rows. 
The problem is comeing in this part of code:
````ts
   if (this.childWidth == undefined || this.childHeight == undefined) {
            contentDimensions = content.children[0] ? content.children[0].getBoundingClientRect() : {
                width: viewWidth,
                height: viewHeight
            };
        }
````
When I load the last time the list, this part of code put height to the same height of the container... it's a bug. How could I fix it?

**Comment by techmind-git** [comment]
Sounds a bit like what I've got on my iPad with the demo page. When scrolling all the way to the top of the list I reach the point when I only see 2 rows when there are more items and I should see a full list. Scrolling a little bit down again does show the other rows again. I don't have this behavior on other devices. A fix would be really appreciated.

**Comment by speige** [comment]
@pedrollanes Would you mind submitting a pull request with your proposed solution? Thanks.

**Comment by speige** [comment]
I wonder if this issue is already resolved in the latest version of the code. Would you mind re-testing & closing this if it's fixed? Thanks.

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
