### ISSUE TITLE
Scroller stops scrolling (using mouse wheel) unless mouse is moved

### ISSUE THREAD

**Issue by Mikli** [rintoj/angular2-virtual-scroll#532]
It seems you can only scroll if mouse is in move. When it's held still, scroller stops to scroll after few records. It's easily reproducible for first live sample from here https://rintoj.github.io/ngx-virtual-scroller/

**Comment by dhemonik** [comment]
+1

**Comment by z3ttee** [comment]
I had the same problem for several weeks. I tried fixing the bug myself without success. However, today I tested the sample page (linked above) again and now it works. Maybe there was a browser bug that has been fixed? Please let me know if you know more.
Also please check your browser version as I am curios why it works for me out of the sudden (I am using MS Edge 103).

**Comment by Mikli** [comment]
agree. Browser bug. Latest Edge works fine.

**Comment by dhemonik** [comment]
It's currently failing on Chrome 102.0.5005.115 right now.
