### ISSUE TITLE
Unable to remove items from list

### ISSUE THREAD

**Issue by twjacobsen** [rintoj/angular2-virtual-scroll#55]
When trying to remove an item from the list, it's not removed until I scroll just a little.

I'm removing entries from the data using `filter`, which will create a new list, so the reference change should be in place.

I've tried triggering `refresh()` manually, no luck.

I'm having a hard time seeing how this does not work, when sorting seems to be somewhat similar.

**Comment by twjacobsen** [comment]
Turns out I needed to use the `async` pipe - so it's a non-issue after all

**Comment by nate-knight** [comment]
@twjacobsen  I still see this issue whether I use an async pipe or not. The code seems to only emit events if the start and end values change. But when I remove an item from the list, those values don't change unless they are all currently visible. Did you have a different solution?

**Comment by insomnia1337** [comment]
bump

**Comment by speige** [comment]
Please create a stackblitz if you want help troubleshooting this issue.
