### ISSUE TITLE
Unable to use with Angular 16

### ISSUE THREAD

**Issue by gora-v2** [rintoj/angular2-virtual-scroll#557]
Hi Team,
Am upgrading my angular project from 13 to 16 and facing some issue with ngx-virtual-scroller can someone please help.

This likely means that the library (ngx-virtual-scroller) which declares VirtualScrollerModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by RajeshMunirathinam** [comment]
> Hi Team, Am upgrading my angular project from 13 to 16 and facing some issue with ngx-virtual-scroller can someone please help.
> 
> This likely means that the library (ngx-virtual-scroller) which declares VirtualScrollerModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

@gora-v2  I hope you can use this module [ @iharbeck/ngx-virtual-scroller ] as an alternative. Which is an extended module from the [ngx-virtual-scroller]. You can check this out!!!

I hope It is just a module update, It doesn't require any code change.

**Comment by gora-v2** [comment]
Hi @RajeshMunirathinam,
Thanks for pointing to the right alternative.
