### ISSUE TITLE
angular material conflict

### ISSUE THREAD

**Issue by sbechet** [rintoj/angular2-virtual-scroll#58]
Hello,

I'm trying to use Material [tab component](https://material.angular.io/components/component/tabs).

All work fine for the first tab but for others :

```
<div _ngcontent-c3="" class="total-padding" style="height: 0px;"></div>
```

Any idea?

**Comment by sbechet** [comment]
Hello, I find a solution forcing childHeight="1".

Maybe can be a default solution?

**Comment by uso5** [comment]
Hi @sbechet,

there is a workaround for this. You should call function that refereshes virtual function on tab change. 

On tab change
`<md-tab-group (selectedIndexChange)="changedTab($event)">`

Define viewchild in component
`@ViewChild(VirtualScrollComponent) private virtualScroll: VirtualScrollComponent;`

On tab change call function
`changedTab($event: any) {
    // whatever index of tab you need, starting from 0
    if ($event == 1) {
      this.virtualScroll.refresh();
    }
  }`

**Comment by speige** [comment]
Closing because a workaround has been suggested. Please re-open if the issue persists.
