### ISSUE TITLE
Can not run ng build --prod

### ISSUE THREAD

**Issue by casillas10** [rintoj/angular2-virtual-scroll#59]
I got the error like this
`ERROR in /MyProject/$$_gendir/node_modules/angular2-virtual-scroll/dist/virtual-scroll.ngfactory.ts (141,35): Supplied parameters do not match any signature of call target.` when I run the `ng build --prod`,
but it work fine for `ng build`.

The environments on my computer are
`Ubuntu 14.04.5 LTS`
`@angular/cli: 1.1.2`
`node: 7.4.0`
`@angular/common: 2.4.10`
`@angular/compiler: 2.4.10`
`@angular/core: 2.4.10`
`@angular/forms: 2.4.10`
`@angular/http: 2.4.10`
`@angular/platform-browser: 2.4.10`
`@angular/platform-browser-dynamic: 2.4.10`
`@angular/router: 3.4.10`
`@angular/cli: 1.1.2`
`@angular/compiler-cli: 2.4.10`

Could you please fix this problem?

**Comment by speige** [comment]
Can you try again with the latest version of the package & let me know if you're still experiencing this?

**Comment by casillas10** [comment]
My project upgraded to Angular 4, It has no trouble. 
Thank you very much.
