### ISSUE TITLE
Multi-column scroll is broken in the demo

### ISSUE THREAD

**Issue by luisaceituno** [rintoj/angular2-virtual-scroll#6]
![2016-12-08_13-18-44](https://cloud.githubusercontent.com/assets/8135999/21009818/fbdbf7ce-bd48-11e6-8589-8f9f274063ef.gif)

This seems to happen when the browser is maximized in a 1080p screen.

**Comment by rintoj** [comment]
It seems like the width calculation has broken. The reason I think is that - the width of scroll bar is not taken into account - which is more for windows. I'm looking into ways to identify the width of scrollbar, without any success so far. If you have any ideas please share.

**Comment by rintoj** [comment]
Fixed. Available with v0.0.7. Feel free to reopen if you still see the problem.

**Comment by abinax** [comment]
HELP! I faced the same problem today in my code

**Comment by speige** [comment]
@abinax please describe your issue & create a stackblitz to reproduce it. This particular issue has been fixed for a long time, so your issue is probably different.
