### ISSUE TITLE
Error in Universal render scenario

### ISSUE THREAD

**Issue by Adam-Langley** [rintoj/angular2-virtual-scroll#64]
Hi,

I am using angular universal, and get this error:
`Call to Node module failed with error: Prerendering failed because of error: ReferenceError: Event is not defined`

I assume this is an issue with attempting to render it on the server.

Any suggestions? 

Note: I am fairly new to ng2

Thanks

**Comment by elitenick** [comment]
Same exact issue here. Event is not defined.

**Comment by elitenick** [comment]
Solved by changing the source code from:
  onScroll(e: Event) {
    this.refresh();
  }

to:
  onScroll(e: any) {
    this.refresh();
  }

**Comment by speige** [comment]
I believe this is resolved in the latest version of the package. Please re-open if you're still experiencing this.
