### ISSUE TITLE
Just an idea for performance

### ISSUE THREAD

**Issue by ghetolay** [rintoj/angular2-virtual-scroll#66]
Hi, First I want to say I don't use that project (yet) but just came across and looked a bit about the source code.

I see you're using a `HostListener('scroll')` and `requestAnimationFrame` (not sure why this one) to apply the refresh. Where the refresh consist of 
1) update `translateY`. 
2) fire update with new items if necessary.

So both those async method will trigger a change detection runs, this means roughly 2 CD per scroll event. This could be a real perf killer !
I think you could get a significant gain if you would 
1) run all async methods outside the angular zone `zone.runOutsideAngular()` (can't use `HostListener ` anymore but needs to register the listener using `Renderer`.
2) update `translateY` yourself using `Renderer`
3) when necessary, emit the update back inside the zone `zone.run()`. 
That way you would trigger a CD only when items needs to change (when update emits).

Just an idea, I may have missed something but hope that helps !

**Comment by rintoj** [comment]
@ghetolay, thanks for this. I will try and let you know how it goes.
