### ISSUE TITLE
Latest Commits are not publish in NPM, can you please publish them?

### ISSUE THREAD

**Issue by naharyd** [rintoj/angular2-virtual-scroll#67]
Latest Commits are not publish in NPM (for example, commit: e8ade26662ac9024b5f7245ca293dfe1d3a60dfc),

Can you please publish them?

**Comment by ktersius** [comment]
Yes please there are bugs that were fixed that has now not been pushed to npm.

The onChanges check https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L109 has been fixed to check for items before accessing length property.

Now running into issue where I change height/width and it tries to access length and throws errors.

**Comment by rdgfuentes** [comment]
@rintoj Great component, thanks a lot for it! It's awesome. We're planning on using it but we'll need to use bufferAmount. Are you planning on publishing your latest changes to NPM? bufferAmount it's not available on angular2-virtual-scroll@0.1.7 (the latest version published in npm). Let me know if there's anything I can do to help/contribute.

**Comment by rintoj** [comment]
@rdgfuentes, published all the changes. The latest version is now v0.2.0. Thanks a lot for your contribution.
