### ISSUE TITLE
data from server

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#7]
ENHANCEMENT 
Hi there awesome lib what's about virtual scroll with data from server ...

something like : http://saulis.github.io/iron-data-table/demo/

when we scroll we call http request to show more data ?

**Comment by rintoj** [comment]
Hi, thanks for your feedback. I'm working on this. We will have this soon.

Related to [#4](https://github.com/rintoj/angular2-virtual-scroll/issues/4)

**Comment by rintoj** [comment]
[Feature](https://github.com/rintoj/angular2-virtual-scroll#loading-in-chunk) added.
