### ISSUE TITLE
Buffer amount feature does not work 

### ISSUE THREAD

**Issue by jeco123** [rintoj/angular2-virtual-scroll#71]
The scrolling behavior is weird when adding this property to the component as if items where not scrolled at the beginning of the list.

**Comment by Marcelh1983** [comment]
changing this.topPadding = d.childHeight * Math.ceil(start / d.itemsPerRow) - (d.childHeight * Math.min(start, this.bufferAmount)); works for me.

I think this.element.nativeElement.scrollTop should corrected the same way. But I didnt notice any difference changing this.
