### ISSUE TITLE
When loading list virtual scroll dont show it

### ISSUE THREAD

**Issue by Worek** [rintoj/angular2-virtual-scroll#73]
Hi.
Im trying to implement this solution to angular2/bootstrap tool.
When im implementing the html code to my list component it wont show. Nothing is shown. Through dev tools i can see the list exist and is transferred to your module. But VS wont send it to its components ( the smallest list is empty ) or send two elements and show it after the padding messing with my style. Always those two elements are after the page, on the bottom. Anyone met this issue?

**Comment by AlexandrZl** [comment]
I have the same issue

**Comment by rintoj** [comment]
I am assuming that you have an issue with the container size. The container element must have: 
1. display: block
2. Predefined height and width

Please read https://github.com/rintoj/angular2-virtual-scroll#if-container-size-change to understand more about this or check out the demo project https://github.com/rintoj/angular2-virtual-scroll/tree/master/demo
