### ISSUE TITLE
Cant find a way to write e2e tests while using this... Is there an example or a way?

### ISSUE THREAD

**Issue by Mohendran** [rintoj/angular2-virtual-scroll#77]
I need to write e2e for an angular app with anguar2-virtual-scroll... But I need a way to write e2e's... Can anyone point me to an example or a way to write it

**Comment by rintoj** [comment]
@Mohendran, can you elaborate the issue you are facing with writing an e2e tests while using angular2-virtual-scroll?

**Comment by Mohendran** [comment]
@rintoj Iam getting values from the api and using infinite scroll methodology.... Iam getting 100 values per api call.... But Iam viewing 10 rows of data.... (I can understand the reason why, 10 rows of data are present in the dom).... But In my e2e tests, I want to access all the data present... How do I accomplish this... Or should I follow any other logic...?

**Comment by rintoj** [comment]
@Mohendran, The whole point of virtual scroll is to render minimal number of dom elements while rendering a list of large number of elements. So I think your test cases must reflect this. However if you want to access all of the data, you must scroll down through list and see if all of that is present.
