### ISSUE TITLE
Can't get even simple example to work

### ISSUE THREAD

**Issue by aaronfrost** [rintoj/angular2-virtual-scroll#78]
Hello all... when I try to get this component to work, it doesn't. I would really love to use it. Any help you can off would be appreciated. I have installed both the latest build, and the current commit in master. Nothing is working. 

When I have my `ngFor` on a `div` it breaks. But when I put it on a span, it works, but they are all on the same line, which doesn't help me. 

I created a new Angular CLI project. This is the only component I have added to that project. So the project is very basic. If you could help me, I would be very thankful. Here is the one component that contains the `virtual-scroll` that isn't showing it. It currently paints the container the right height. But it doesn't show any of the items in the container. Please help. 

```javascript
import { Component, OnInit } from '@angular/core';

const Items = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

const template = `
<h5>Hey Dawg!</h5>
<virtual-scroll 
[items]="myItems" 
(update)="scrolledItems = $event"
[childHeight]="18"
[childWidth]="40"
>
  <div *ngFor="let item of scrolledItems" class="hey-dawg">{{item}}</div>
</virtual-scroll>
`;

@Component({
  selector: 'af-list',
  template,
  styles: []
})
export class ListComponent implements OnInit {

  myItems = Items;

  constructor() { }

  ngOnInit() {
  }

}


```

Here is a repo with my stuff. Please let me know if you can help me get this working. https://github.com/aaronfrost/testvirtualscroll

**Comment by nkyordy** [comment]
It looks like you just missed some CSS. I nested it in a parent div and defined a border, width, and height to make it easier to see.

I created a pull request for you.

**Comment by aaronfrost** [comment]
I love you @nkyordy! Thank you for the help.
