### ISSUE TITLE
Simply will not work.

### ISSUE THREAD

**Issue by ScottSpittle** [rintoj/angular2-virtual-scroll#79]
I've followed all the demos and documentation and simply cannot get this to work.
I wanted to have a list of n items and render more as I scrolled.

**Comment by marcosanfilippo** [comment]
I have the same issue! I follow the demo and nothing works!
The scroll with fetch is very interesting. Unfortunately nothing works.

**Comment by ronzeidman** [comment]
It should work for this scenario. I used it for the exact same scenario.
Notice that that the scroll element should have a size without items, I guess you have a css issue.

**Comment by marcosanfilippo** [comment]
@ronzeidman I can't get it working. My issue is that if I have 20 elements, I cant limit it to show 5 (for example). How can achieve that?

**Comment by ronzeidman** [comment]
You can limit the viewport height (set its height to the height of 5 elements), It will only show the number of items that fit into that height (even though the scroll will hint you have more) you can see the created elements on the dev-tools inspector.

**Comment by rintoj** [comment]
@ScottSpittle, @marcosanfilippo, can you share your code?

**Comment by kykint** [comment]
Virtual scroll will not work in any of these cases:
1. Virtual scroll doesn't have height or max-height
2. Inner elements don't have height (e.g. they are inline elements) 
In other cases this component works very well

**Comment by sanjaybhaskar** [comment]
I'm having the same issue. it renders all the items from the list. here is my repo
https://github.com/sanjaybhaskar/virtual-scroll

**Comment by ScottSpittle** [comment]
@whyboris Sorry for the hanging reply. I got this to work no problem. Thanks for the updates though.

**Comment by speige** [comment]
Closing since the issue appears to have been user error & appears to have been resolved. Please re-open if the issue continues.
