### ISSUE TITLE
example of 1mio

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#8]
your virtual scroll seems cool, can you make an example with 1mio :)  or 100k rows ? This will show your perfs to users

enhancement: Does it supoprt AoT

great work

**Comment by rintoj** [comment]
Hi, Thanks for your feedback. Sure, I will update the demo soon. I will check on AoT as well.

Cheers.

**Comment by istiti** [comment]
@rintoj hm I hope in a few days I can use your lib in our project.  
Another thing: since angular use semver In a few month angular3 will be available, so you could rename your lib into 
rintoj-virtual-scroll

or ng- prefix, even if it's reserved for internal core, maybe:
ng-virtual-scroll  
ng-virtual-repeat

**Comment by rintoj** [comment]
added `-webkit-overflow-scrolling: touch;` with #13. Soon this will be ported to [ng-virtual-scroll](https://www.npmjs.com/package/ng-virtual-scroll)

**Comment by istiti** [comment]
@rintoj  you close here ? what about big number of rows
