### ISSUE TITLE
Limit amount of item / nodes to show

### ISSUE THREAD

**Issue by marcosanfilippo** [rintoj/angular2-virtual-scroll#80]
The provided example doesn't show how to limit the item / node. 

In a list of 50 items, 15 are listed and others go into the scroll. How to limit to 5, for example?

**Comment by rintoj** [comment]
The number of items to be listed is decided by the height of the container. In your case 15 is the number auto calculated by the component, considering height of the container and height of each element. To limit to 5 you must reduce the height of the container
