### ISSUE TITLE
Not working. Rendering all the items

### ISSUE THREAD

**Issue by sanjaybhaskar** [rintoj/angular2-virtual-scroll#89]
Virtual scroll renders all the items from the list. here is my repo to reproduce
https://github.com/sanjaybhaskar/virtual-scroll

**Comment by huybn5776** [comment]
Just three line you need to add.
recent.component.ts - >
`constructor(r: Router, public dataService: DataService,private apiEvent: ApiEvent,
              private  mdlLayout:MdlLayoutContentComponent){
    this.router = r;
    let rlcmodel = new rlcModel();
    this.rlcObject = rlcmodel.rlcObject;
  }`

recent.component.html ->
`<virtual-scroll [items]="rlcObject" (update)="viewPortItems = $event"
                [childHeight]="72"
                [ngStyle]="{'height.px':mdlLayout.el.offsetHeight}">
    <mdl-list>
        ......
`
[recent.zip](https://github.com/rintoj/angular2-virtual-scroll/files/1228386/recent.zip)

Specify the height of VirtualScroll, and it's childHeight to make it work. :)

**Comment by franzeal** [comment]
I had a similar issue, however the proposed solution wasn't working for me.

My scenario is I have a flexbox with a percent height that the virtual scroll is intended to fill the remaining space of (has a some form elements above it).  I could nest flexboxes in to get the virtual scroll to take the remaining height, but that only worked in Chrome and not IE11 and FF.

My virtual scroll is wrapped by another component (represented by the inner div below).  Essenetially what ended up working for me (and remain pure CSS) was to lose the nested flexbox I had been using  to get the nested component/virtual scroll to fill the height (but only worked in Chrome).

From:
```html
<div style="height:50%; display:flex; flex-direction:column">
  <input type="text" style="flex:none">
  <div style="display:flex; flex-direction:column; flex:auto">
    <virtual-scroll style="flex:auto">
    </virtual-scroll>
  </div>
</div>
```

To:
```html
<div style="height:50%; display:flex; flex-direction:column">
  <input type="text" style="flex:none">
  <div style="position:relative; flex:auto">
    <virtual-scroll style="position:absolute; height:100%; width:100%">
    </virtual-scroll>
  </div>
</div>
```

**Comment by speige** [comment]
Closing since there are proposed workarounds & this is most likely user error due to not following the documentation properly, since it's working for most users. Please re-open if you continue to experience problems.
