### ISSUE TITLE
external control of start index

### ISSUE THREAD

**Issue by ivob52** [rintoj/angular2-virtual-scroll#9]
Hi,

Thank you for your excellent component for virtual lists!

It will be cool if there is control over the starting position of the list.
By example - a "startIndex" input property.

**Comment by rintoj** [comment]
Hi, 

Thanks for your feedback. Sure I will add  `startIndex` and publish soon.

**Comment by istiti** [comment]
any eta

**Comment by vitoexe** [comment]
at this moment You can use __scrollInto__ method, usage is similar to __refresh__,    
https://github.com/rintoj/angular2-virtual-scroll#if-container-size-change
```js
this.virtualScroll.scrollInto(this.items[69]);
```

**Comment by rintoj** [comment]
@ivob52, adding a `startIndex` messes up the internal logic of the component. Problem is, this input should be used only at the startup of the component. If component ignores the changes to `startIndex` at run time, it become hard to reason the scroll-logic.

I think, @vitoexe's suggestion achieves the same through `scrollInto`. So I am thinking that's the way to go about.
