### ISSUE TITLE
Using with Angular Material data table?

### ISSUE THREAD

**Issue by vapits** [rintoj/angular2-virtual-scroll#92]
Hi guys,
amazing module!

I was trying to make it work with Angular Material data table (https://material.angular.io/components/table/overview) though it seems quite tricky. So I was wondering if there is available any example for this module to work with material data table. 
That will be awesome!

**Comment by sbechet** [comment]
Did you look #58?

**Comment by speige** [comment]
I think #58 is unrelated as that's tab, not table.

Unfortunately we don't have an example on how to do this. Your best bet is troubleshooting it on your own, google searching, & stackoverflow. If you come up with a working example, feel free to post it here for future users to read. Thanks.
