### ISSUE TITLE
 Bug. List not showed if has one element. Is [childHeight] not set.

### ISSUE THREAD

**Issue by nickorsk2017** [rintoj/angular2-virtual-scroll#93]
Bug. List not showed if has one element. (Chrome browser tested)
P.s. Best module)

**Comment by rintoj** [comment]
It works for the demo project (within this repo). Please see the screenshot below.

![image](https://user-images.githubusercontent.com/10824903/30102038-fd90eb9e-930b-11e7-8736-059f2c906cdc.png)

**Comment by tolemac** [comment]
The same here...

With one:
![image](https://user-images.githubusercontent.com/247167/34467448-765b80a6-eef2-11e7-8a91-e75fa4824d13.png)

With two:
![image](https://user-images.githubusercontent.com/247167/34467452-a8da3ac2-eef2-11e7-9593-98bd40257d09.png)

**Comment by tolemac** [comment]
I'm not sure but I think is about calculate `childHeight` calculation on `calculeDimensions`.

I have solve it adding this to the template:

````html
    <div class="total-padding" #shim></div>
    <div class="scrollable-content" #content>
          <div *ngIf="!viewPortItems || viewPortItems.length == 0" style="height: 10px"></div>
          <ng-content></ng-content>
    </div>
````
