### ISSUE TITLE
bufferAmount does not exist on element AOT - latest 2.1

### ISSUE THREAD

**Issue by evanjmg** [rintoj/angular2-virtual-scroll#96]
Template parse errors:
       Can't bind to 'bufferAmount' since it isn't a known property of 'virtual-scroll'.
       1. If 'virtual-scroll' is an Angular component and it has 'bufferAmount' input, then verify that it is part of this module.
       2. If 'virtual-scroll' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
       3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
       [items]="results"
       [childWidth]=""
       [ERROR ->][bufferAmount]="2"
       (update)="viewPortItems = $event"
       (change)="changeEvent($event)">

**Comment by evanjmg** [comment]
Current workaround - downgrade to 1.8

**Comment by rintoj** [comment]
This should now be fixed. Latest v0.3.0. Please reopen if this isn't.
