### ISSUE TITLE
Request: smooth scrolling

### ISSUE THREAD

**Issue by twjacobsen** [rintoj/angular2-virtual-scroll#98]
Hi,

Would it be possible to do one of the following?

Either a) scroll smoothly when using `scrollInto`
or b) providing a method to get the scroll-distance, and have the consumer of the plugin do the scrolling

Thanks

**Comment by rintoj** [comment]
Hi @twjacobsen, added smooth scroll for `scrollInto` and published (v0.3.0). Check the demo here: http://rintoj.github.io/angular2-virtual-scroll/#samples. Please note I have added a **Scroll to 50** button

**Comment by twjacobsen** [comment]
Looks good in the demo, but I don't see the 0.3.0 release anywhere here on github?
