### ISSUE TITLE
Request: Item headers

### ISSUE THREAD

**Issue by markv** [rintoj/angular2-virtual-scroll#99]
Is it possible to add in the ability to define headers for groups of items which would be a fixed height?

**Comment by rintoj** [comment]
@markv, it is possible, but with some limitations. 

1. The header must be one of the items in the list. You may declare a property with a flag to represent header.
2. The height of the header must match almost the item. (just try with different heights until you get it right)

With these two things taken care, you must be able to define group headers. Please feel free to reopen this if you running into issues with this approach.
